### ISSUE TITLE
Error when cloning in Windows

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#1]
Hello,
Your configuration won’t load and crash on Windows at install.

See image below.
![emacs201](https://user-images.githubusercontent.com/5302343/207658521-d930574c-6f04-44fe-88d0-f572c7700d7b.png)

**Comment by abougouffa** [comment]
Hi @raylemon , thank you for the feedback. 

I'm using the config principally in a Linux machine. However, I did test it in a Windows 10 machine, it worked with some limitations (some issues with tree-sitter and dirvish-fd).

It seems to me that this error is caused by `straight.el`. Try to remove the `.emacs.d/local` folder and try again.

By the way, what version of Emacs you are using? and how you installed it (using Gnu installer, MSYS2?).

**Comment by raylemon** [comment]
I use emacs 29 build with Msys2 on Windows 11.
The bug is due to version of emacs. I have tested with vanilla emacs 28 (installed with **winget** tool) and it works.

I use your doom config in Windows (with some adjustements), and i love your config (mainly for ltex-lsp).

**Comment by abougouffa** [comment]
Thanks for the feedback, great to hear that!

For the `ls` command, I've fixed it in my test machine by adding `C:\MSYS2\usr\bin` (where there is a version of `ls` with other Unix-like commands) to the `Path` environment variable (from `Win+R`, `SystemPropertiesAdvanced`, click `Environment Variables`).

I hope it helps!

**Comment by raylemon** [comment]
Thanks for the quick reply ! 
So, another problem, linked to this : if I want to use chemacs 2 to have your config and doom config, I can’t use your config with another folder than .emacs.d

**Comment by abougouffa** [comment]
I don't think that the current config works with Chemacs2, in Emacs 29+ thought, there is a new option `--init-directory` which should work!

**Comment by raylemon** [comment]
Thanks again, I’ll investigate this !!

**Comment by abougouffa** [comment]
After taking a look at my old Chemacs2 configuration, I would say that you can specify your MinEmacs directory in Chemacs2's `~/.emacs-profiles.el` like this:

```elisp
(("doom"      . ((user-emacs-directory . "path/to/your/doom/clone")
                 (env . (("DOOMDIR" . "~/.doom.d")))))
 ("minemacs"  . ((user-emacs-directory . "path/to/your/minemacs/clone")
                 (env . (("MINEMACS_DIR" . "~/.minemacs.d"))))))
```

In MinEmacs, all directories are defined with respect to `user-emacs-directory`, so if this one is set properly by Chemacs2, it should work!

**Comment by abougouffa** [comment]
I'm assuming this issue is resolved, please feel free to reopen it if you still face this problem.
