### ISSUE TITLE
latexmk with lualatex

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#10]
There is a way to use latexmk with -pdflua switch with shortcut SPC m c ?

Thanks

**Comment by abougouffa** [comment]
You should just set `TeX-engine` to `luatex` in your LaTeX buffer. This is a buffer-local variable, so you need to:

- set it in the LaTeX buffer by `SPC ;` then type `(setq TeX-engine 'luatex)` `RET`.
- or set it in your `.dir-locals` `SPC b v d`, type `LaTeX-mode` `RET`, then `TeX-engine` `RET` and type `'luatex` `RET` and save the created `.dir-locals` file.
- or if you want `TeX-engine` to be `luatex` by default, add this to your `config.el`:

```elisp
(with-eval-after-load 'tex
  (setq-default TeX-engine 'luatex))
```
