### ISSUE TITLE
+writing-mode can not open

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#103]
hi @abougouffa 
got error when **SPC t w**
set: Symbol’s value as variable is void: org-format-latex-options

**Comment by abougouffa** [comment]
Hell @donneyluck ,

Please launch Emacs with `MINEMACS_DEBUG=1 emacs` or `emacs --debug-init` and attach the error's backtrace.

**Comment by abougouffa** [comment]
Should be fixed now!
