### ISSUE TITLE
[BUG] Sortie intempestive du mode insertion

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#106]
**Describe the bug**
Ce bug est "bizarre" , intermittent et intempestif. Pourtant, si j’active eglot, il disparait (ou il me gêne moins, impossible à dire).
Quand je suis en mode insertion et que je tape mon texte (en org-mode), de temps en temps, Emacs repasse en mode normal, puis repasse en mode insertion. Sauf qu’il fait ça tout seul, pendant la frappe. Ce qui fait que souvent, j’active une combinaison de touches (souvent inconnues, heureusement).

Ça arrive plusieurs fois par minute. Je suppose qu’il y a un traitement qui s’effectue et qui a besoin de passer en mode normal.

**To Reproduce**
1. Taper du texte en emacs (sans eglot actif)
2. Espérer voir le bug arriver

**Expected behavior**
Pas de sortie intempestive

**Backtrace**
Pas de backtrace

**Comment by raylemon** [comment]
Aussi, il manque un "s" au texte
`Org async export finised, see *Org Export Process* for more details.` ;)

**Comment by abougouffa** [comment]
Salut @raylemon , 

Merci pour ce retour!

C'est effectivement bizarre comme comportement.

Dans le texte que vous tapez, il n'y a pas par hasard une combinaison de `"jk"` ou `"kj"` suivi un peu plus tard par un `"i"` ?

Si c'est le cas, c'est un comportement normal (et prévisible). Il s'agit de `evil-escape` qui permet de configurer une séquence de deux caractères permettant d'émuler la touche `ESC` dans `evil-mode`. C'est parfois pratique de taper juste `jk` ou `kj` pour sortir du mode `insert` au lieu de faire bouger la main vers le `ESC`.

Vous pouvez tester ce bout dans votre `modules.el` pour désactiver le paquet `evil-escape` et sa configuration, puis voir si le bug disparaît.

```elisp
;; Disable `evil-escape`
(push 'evil-escape minemacs-disabled-packages)
```

**Comment by raylemon** [comment]
Alors, non, je ne tape pas la combinaison "kj" ou "jk", ça arrive en tapant du texte en français banal. Et dès que eglot est actif, le problème disparait. Bon, c’est pas trop ennuyant, sauf quand j’active une fonction inconnue sans le vouloir :)

**Comment by abougouffa** [comment]
Quand vous lancez Emacs en mode debug `MINEMACS_DEBUG=1 emacs`, il n'y a pas d'informations supplémentaires affichées dans `*Messages*` lorsque cela arrive?

Je n'ai pas réussi à reproduire ce bug sur ma machine.

Vous pouvez essayer de lancer Emacs avec `MINEMACS_IGNORE_USER_CONFIG=1 emacs` pour ignorer le contenu de `config.el`. Puis, vous pouvez essayer de reproduire le bug, si ce dernier disparait, il est fort probable qu'il a été cause par une config particulière dans votre `config.el`.

**Comment by abougouffa** [comment]
Vous avez essayé de lancer Emacs avec `MINEMACS_IGNORE_CONFIG_EL=1 emacs`?

Je n'ai pas réussi de reproduire le bug sur ma machine, j'aimerais écarter la possibilité que ça soit un problème lié seulement à votre `config.el`.

**Comment by raylemon** [comment]
Oui, j’ai désactivé le config.el via la commande.
J’ai aussi désactivé evil-escape. Le problème est toujours présent… Je ne vois pas comment je peux suivre le problème ni fournir une backtrace…

**Comment by raylemon** [comment]
D’autant que si j’active eglot, le comportement disparait…
Après, c’est peut-être un comportement bizarre dû à Windows…

**Comment by raylemon** [comment]
Bonjour,
Non, le problème est persistant, et je n’ai aucune piste pour comprendre d’où il vient.

**Comment by abougouffa** [comment]
Bizarre, j'ai jamais rencontré un bug pareil. J'avoue que je n'ai pas testé MinEmacs (ni Emacs) sur Windows.

Tu n'as pas de customisation specifique à Org mode dans ton `config.el`?

**Comment by raylemon** [comment]
J’ai copié "tel quel" ton config.el du skel en modifiant les quelques paramètres utiles pour moi, notamment en ajoutant des éléments d’export latex.

Je n’utilise emacs que pour la rédaction en org-mode et latex. J’ai une ligne de code concernant eglot, afin qu’il retrouve l’exécutable ltex-ls…

**Comment by abougouffa** [comment]
Bizarre, il me semble qui c'est un problème en relation avec `evil` ou les packages tiers `evil-*`.

Tu peux essayer de voir ce qu'il y a comme packages `evil-*`, les ajouter dans `minemacs-disabled-packages` dans ton `modules.el`. Si cela règle le problème, essaie de commencer à enlever les packages de la liste des packages désactivés un par un jusqu'à que le bug réapparaît.

J'ai fait quelques tests sur une machine virtuelle Windows 11 + Emacs 29 mais je n'ai pas pu reproduire ce bug.

**Comment by raylemon** [comment]
Le problème semble résolu, ou du moins il n’apparait plus… peut-être était ce dû à un souci de Windows réglé avec une mise à jour ?
