### ISSUE TITLE
Support for Emacs 28.1

### ISSUE THREAD

**Issue by mandarvaze** [abougouffa/minemacs#11]
I'm on macOS Catalina (10.15.7) and unable to upgrade emacs (brew does not support this version anymore)
So I'm stuck with emacs 28.1

Are there specific features in 28.2 (that are not in 28.1) which are required for minemacs ?

FWIW, I got minemacs working on Emacs 28.1 by changing [this line](https://github.com/abougouffa/minemacs/blob/main/init.el#L8)
I'll leave it up to you whether you want to support this lower minor version or stick to 28.2

**Comment by abougouffa** [comment]
MinEmacs should work on Emacs 28.1, I fixed the version just because in my testing VM I have 28.2 (the tested version).

I've edited the condition to accept versions from 28.0.50 to 28.2 without signaling an error.
