### ISSUE TITLE
[BUG] org-element--parse-buffer petit souci

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#110]
**Describe the bug**
Le message suivant apparait brièvement à chaque fois que j’utilise la touche backspace
`org-element--parse-buffer: Suppressed 'M-x keyboard-quit'. Press 'M-x keyboard-quit' 4 more times to force interruption.`

**Emacs version**
Run `M-x emacs-version` and put its output here: 29.1 Windows

**Checkup list**
- [X ] You've tested disabling your `config.el` using `MINEMACS_IGNORE_CONFIG_EL=1 emacs`?

**To Reproduce**
1. Écrire du texte
2. Taper sur backspace
3. Voir l’erreur (brièvement)

**Comment by abougouffa** [comment]
Salut @raylemon ,

À première vue, il me semble que c'est un message indicatif et que ça ne reflète pas un bug. Je n'arrive pas à le reproduire sur Linux, donc je suppose que c'est spécifique au Windows.

Essaye de `M-x org-element-cache-reset`, ça pourrait régler pas mal d'erreurs liées à `org-element`.

**Comment by raylemon** [comment]
Je vais essayer. Merci !
