### ISSUE TITLE
why this icon can not show 

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#112]
emacs 29.1
![image](https://github.com/abougouffa/minemacs/assets/122257591/5f3b7596-4940-4c66-987a-8c61dd8ce981)

Hi, sorry to bother you. I know this question may be simple, but I have been trying for a long time. Why can’t this character be displayed normally?

**Comment by abougouffa** [comment]
What font you are using?

**Comment by donneyluck** [comment]
![image](https://github.com/abougouffa/minemacs/assets/122257591/d2aae6ab-1684-4083-bb6b-979d66ff4409)
i use this one
jb font

**Comment by abougouffa** [comment]
Maybe it doesn't support this Unicode glyph. Try to change the font to one of a Nerd Fonts patched font.

**Comment by abougouffa** [comment]
Which OS you are using?

**Comment by donneyluck** [comment]
> Which OS you are using?

manjaro i3wm

**Comment by donneyluck** [comment]
![image](https://github.com/abougouffa/minemacs/assets/122257591/ed539c74-3b1b-4feb-9c44-36cc710d7236)
i test the font ttf-iosevka-fixed-curly-slab  but still not work

emacs 29.1    /configure --with-native-compilation=aot --with-tree-sitter

**Comment by donneyluck** [comment]
I found the problem.
1. The unicode-font package was not successfully installed. The ensure t field may be required
2. +unicode-fonts-setup not executed correctly  when minemacs-after-startup  
    then i try  M-x  +unicode-fonts-setup   got some error

**Comment by abougouffa** [comment]
Hello @donneyluck ,

The `unicode-fonts` configuration is now obsolete, I'm not using it in my machine and the font shows fine. It can be interesting for non-latin languages, but in my daily use, I didn't find any usefulness for it. 

I've changed the glyph used to replace the `project-` prefix, so it should display correctly now.

**Comment by donneyluck** [comment]
ok, it can be displayed normally now, but I want to find out why some characters cannot be displayed. Is it supported by my font?

**Comment by abougouffa** [comment]
I don't know the exact reason, some fonts do not support additional Unicode glyphs, and if you are using `unicode-fonts`, you need to install extra fonts for it to work correctly (as specified in the `unicode-fonts` project README).

I'm using Emacs 29.1 on a Manjaro Linux machine, with the `"Iosevka Fixed Curly Slab"` font and without the `unicode-fonts` package, and all is working fine.

**Comment by donneyluck** [comment]
ok I understand. There should still be some fonts missing. Thank you for your help.
