### ISSUE TITLE
[BUG] about tree-sitter

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#114]
**Describe the bug**
tree-sitter   not work  
protobuf-ts-mode

**Emacs version**
Run `M-x emacs-version` and put its output here:
GNU Emacs 29.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-09-01

**To Reproduce**
1. add this in config.el  
```
(use-package protobuf-ts-mode
  :straight t
  :ensure t
  :mode ("\\.proto\\'" . protobuf-ts-mode))
```
2.open one proto file

**Screenshots**
![image](https://github.com/abougouffa/minemacs/assets/122257591/507e5340-10b3-4d27-8af1-982cd0475188)
![image](https://github.com/abougouffa/minemacs/assets/122257591/ba17f1e9-6e55-414f-ad79-2d17167b6906)
this file already in protobuf-ts-mode 
but It seems that the syntax tree is not effective and there is no color keyword prompt.

![image](https://github.com/abougouffa/minemacs/assets/122257591/12c5d96a-702a-47aa-8572-169cf0acd8ca)

I also tried other languages, such as c#, although the csharp-ts-mode & so files are already there, but the syntax is still not colored, and it still doesn’t seem to work.

![image](https://github.com/abougouffa/minemacs/assets/122257591/a473e638-1fef-42c3-9a22-2960878d5606)

**Additional context**
When I open the proto file or switch protobuf-ts-mode, I will be asked to download libtree-sitter-protobuf.so* every time
tree-sitter not work well
M-x treesit-auto-install-all    
It keeps prompting that protobuf has downloaded the .so file in time.

**Comment by donneyluck** [comment]
I tested it with c++ & c treesit and it works fine but there are some issues with csharp and protobuf I know you don't use these thanks for your time

**Comment by abougouffa** [comment]
I've just tried this and it seems buggy. After installing `protobuf-ts-mode` and opening a `.proto` file, `treesit-auto` keep asking to download the library (even though it is installed).

I will temporarily disable `protobuf-ts-mode` in `treesit-auto` until it gets fixed upstream.

@donneyluck Can you please open an issue in the [`treesit-auto`](https://github.com/renzmann/treesit-auto/) upstream repo?

**Comment by donneyluck** [comment]
ok i will open an issue in the [treesit-auto](https://github.com/renzmann/treesit-auto/) upstream repo
