### ISSUE TITLE
[BUG] Impossible d’ouvrir un fichier [SPC . ] ?

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#115]
**Describe the bug**
Le raccourci SPC . utilisé pour ouvrir un fichier n’existe plus.

**Emacs version**
29.2 (Windows)

**Checkup list**
- [X ] You've tested disabling your `config.el` using `MINEMACS_IGNORE_CONFIG_EL=1 emacs`?

**To Reproduce**
1. Ouvrir Emacs
2. Taper SPC .
3. Erreur

**Expected behavior**

**Backtrace**
If the bug rises an error, please attach the full backtrace. To be sure to obtain a backtrace, you should launch Emacs with `MINEMACS_DEBUG=1 emacs` or `emacs --debug-init`.

**Screenshots**

**Additional context**

**Comment by abougouffa** [comment]
Bonjour @raylemon 

Je ne me rappelle pas avoir configuré `SPC .`, C'est `SPC :` qui est utilisé pour ouvrir un fichier dès le début!

**Comment by raylemon** [comment]
Bonjour :)
Sur mon clavier BÉPO, le . et le : sont sur la même touche, mais je n’appuyais pas sur la majuscule. Je le ferai désormais :)
Il y a un moyen d’afficher (ou mieux, d’exporter) tous les raccourcis claviers ? Il y en a tellement, notamment pour org-mode…

**Comment by abougouffa** [comment]
Bonjour @raylemon,

Yep, `SPC h g` fait exactement ça!
