### ISSUE TITLE
[suggest]  about +writing-mode

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#117]
hi @abougouffa 
This mode is great, I like it very much, but there are a few minor issues
Writing-mode will exit when I switch files and need to be turned on again. Is there any way to change this mode switch to global?

**Comment by abougouffa** [comment]
Hello @donneyluck, thanks for the feedback

Yep, the current implementation works like a minor mode that can be enabled in a per-buffer basis. I will try to add an option to enable it globally when I get some free time. I will leave this issue open until then.

**Comment by abougouffa** [comment]
@donneyluck Can you try the new `+writing-global-mode` ?

**Comment by donneyluck** [comment]
I tested it and there was no problem. Thanks  : )
