### ISSUE TITLE
[BUG] No more dashboard after update - me-eaf.el probably missing ?

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#119]
**Describe the bug**
After upgrading Minemacs, dashboard and theme are not displayed. The buffer showns is "pscratch".

**Emacs version**
```GNU Emacs 29.1 (build 2, x86_64-w64-mingw32) of 2023-08-19``` Windows version.

The bug exists too in Linux version (fresh install for testing)

**Checkup list**
- [X ] You've tested disabling your `config.el` using `MINEMACS_IGNORE_CONFIG_EL=1 emacs`?

**To Reproduce**
1. Update or Install Minemacs
2. Waiting launch
3. See error

**Expected behavior**
Dashboard and theme are shown correctly.

**Backtrace**

```elisp
﻿⛔ Warning (initialization): An error occurred while loading ‘c:/Users/big04/.emacs.d/init.el’:

: [MinEmacs:Error] Cannot load "c:/Users/big04/.emacs.d/modules/me-eaf.el", the file doesn’t exists.

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

```

**Comment by donneyluck** [comment]
look file   skel/module.el     me-eaf.el move to  modules/obsolete/me-eaf.el

but the dashboard can not open still
