### ISSUE TITLE
Error: Projectile cache ’~/.emacs.d/local/projectile/known-projects.el’ not writeable

### ISSUE THREAD

**Issue by mandarvaze** [abougouffa/minemacs#12]
I get this error when I added new project
Turns out I didn't have `projectile` folder under `~/.emacs.d/local/`  - Manually creating it fixed the error.

@abougouffa Any idea why it didn't get created automatically ?

**Comment by abougouffa** [comment]
Hello @mandarvaze ,

I use `+directory-ensure` to create `projectile`'s files, this should ensure creating the directory if it doesn't exist.

https://github.com/abougouffa/minemacs/blob/b80717cde12acfc8e102ad29e3308f4c01124c70/modules/me-project.el#L45

However, I suspect you've launched a vanilla Emacs before running MinEmacs, `projectile` can create the *FILE* `~/.emacs.d/local/projectile` which has the same name as the directory `~/.emacs.d/local/projectile/` used in MinEmacs.

In all cases, I didn't manage to reproduce the error on my machine!
