### ISSUE TITLE
[suggest] about font set

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#120]
hi @abougouffa 
The font setting of emacs has always been a headache, especially for languages ​​​​such as Chinese, English, Japanese and Korean.
Here is a solution I saw
So I want to ask you to see if you can add to minemacs
By the way, it can solve my problem that Chinese and English fonts are not equal in width and height.
Thks 

here is the code
https://github.com/seagle0128/.emacs.d/blob/24aefae42f6bdefcb2638e7836d75feca4803fe4/custom-example.el#L34-L85

**Comment by abougouffa** [comment]
Thank you for the suggestion. 
I will take a look to see how can I integrate this effectively!

**Comment by abougouffa** [comment]
Hi @donneyluck 

I've changed how MinEmacs handles fonts. Take a look at `skel/config.el` if you want to customize the fonts. Now by default, there is a set of fonts (default, arabic, han, ...), I've taken the font list from the example you provided.

Thanks again for this suggestion and let me know if it doesn't work for you!

**Comment by donneyluck** [comment]
it works very well thank you very much

**Comment by abougouffa** [comment]
For the moment the only supported settings are `:family` and `:height`. I will try to refactor the code to accept additional parameters in the future.

**Comment by abougouffa** [comment]
Hello @donneyluck 

Now you should be able to pass extra arguments like `:weight` and so on.

**Comment by donneyluck** [comment]
@abougouffa  Thanks again
