### ISSUE TITLE
[BUG] treemacs Can't use keys space

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#123]
@abougouffa hi
I found that treemacs uses treemacs-evil which is very convenient
But I found that in treemacs, it is impossible to operate by pressing key **space** to bring up the menu.

**Comment by abougouffa** [comment]
Yep, I've noticed it, but since I'm not using it I didn't look for a solution. I will check it later

**Comment by abougouffa** [comment]
It should be fixed now. It turned out that the `treemacs-evil` package
