### ISSUE TITLE
[BUG]  about consult-yank

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#124]
hi @abougouffa 
when  press key  y  or d   to copy or delete some content
then call consult-yank 
The first line is always a space and the second line is the cut content.

![image](https://github.com/abougouffa/minemacs/assets/122257591/aaac6fd4-7a17-460e-9fb8-302b4d796599)

**Comment by abougouffa** [comment]
Yep, I confirm I have I a similar behavior. However, I think this should be reported in consult's repo!

**Comment by donneyluck** [comment]
OK I will submit this bug to consult

**Comment by donneyluck** [comment]
https://github.com/minad/consult/issues/888    
maybe killring has some whitespace
