### ISSUE TITLE
[BUG] about magit

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#125]
hi@abougouffa 
Before I used magit to submit the code, everything was fine and no password was required.
Recently I found that when I submit, the following prompt will appear:

**password or token for user my-username**
![image](https://github.com/abougouffa/minemacs/assets/122257591/3f5625fd-b3e8-4881-aaa1-2a6a71b60af8)

I tried entering the token or password but couldn't submit it.

**Comment by donneyluck** [comment]
I found the problem, it's related to this code
When I comment it out, everything works fine
https://github.com/abougouffa/minemacs/blob/main/skel/config.el#L255-L273

**Comment by abougouffa** [comment]
Yes. This is not a bug, it is an example of how you can use `linjira2`. **You are not supposed to use `skel/comfig.el` as it is**. You need to copy it to `~/.minemacs.d/config.el` and remove the irrelevant examples.
