### ISSUE TITLE
[question]  How to replace search results

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#126]
hi @abougouffa 
I want to ask about your workflow
For example, I press the **space s s**  search "test code"
then I want to replace the search results in all matching files in the minibuffer. 
How should I do this?

like this https://hungyi.net/posts/doom-emacs-search-replace-project/

**Comment by abougouffa** [comment]
In my workflow, if I want to search and replace in a project. I use `project-query-replace-regexp` (bound to `SPC p s r`).

The link you gave seems to be specific to Doom Emacs, [I've seen Doom's Vertico config](https://github.com/doomemacs/doomemacs/tree/master/modules/completion/vertico), and it contains a bunch of functions to do search and replace with Embark. It is too complex, and for the moment, I'm not relying on Embark (I don't understand it well!). So, I'm not planning to add a feature like this at the moment.

Please note that there is a [Discussions](https://github.com/abougouffa/minemacs/discussions) tab where you can ask questions. Issues should be opened only for bugs.

**Comment by donneyluck** [comment]
I tried project-query-replace-regexp 
It suits my needs very well. Doom's method is too complicated.
[Discussions](https://github.com/abougouffa/minemacs/discussions) 
I have asked questions before but there has been no reply for a long time. Maybe you are busy. I will go there to ask questions next time. Thanks again.

**Comment by abougouffa** [comment]
Sorry, didn't see it. Maybe I have to tweak my GitHub notification settings
