### ISSUE TITLE
[BUG] [Windows] Emacs freeze on file recovery

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#133]
**Describe the bug**
When I want to open a project who has crashed before, minemacs totally freezes with this text:
``` elisp
file.org has auto save data; consider M-x recover-this-file
```
Impossible to use emacs, after that, I’m forced to kill processes

**Emacs version**
Run `M-x emacs-version` and put its output here: 29.1 (Windows)

**Checkup list**
- [X] You've tested disabling your `config.el` using `MINEMACS_IGNORE_CONFIG_EL=1 emacs`?

**To Reproduce**
1. Open minemacs
2. Trying to restore any file

**Expected behavior**
Emacs running smoothly

**Backtrace**
If the bug rises an error, please attach the full backtrace. To be sure to obtain a backtrace, you should launch Emacs with `MINEMACS_DEBUG=1 emacs` or `emacs --debug-init`.

No backtrace available

**Comment by abougouffa** [comment]
Hello @raylemon 

Seems weired to me!

Can you try to run `make clean` in MinEmacs' directory? Or manually delete `~/.minemacs.d/local/cache`.

**Comment by raylemon** [comment]
Je passe en français…
J’ai supprimé le dossier `cache`. Après recompilation des paquets, j’ai tenté de rouvrir mon fichier, et emacs m’a encore indiqué `recover-this-file` avant de crash et de se fermer. Je relance et je reviens exactement au même point que précédemment: freeze et impossible d’effectuer la moindre action.

J’en ai profité pour faire l’update (en réalité, j’ai une macro qui fait l’update de minemacs avant de le lancer)

**Comment by abougouffa** [comment]
Salut @raylemon,

C'est bizarre, ça arrive sur tous les fichiers Org ou seulement sur un fichier particulier?

## Une piste pour déboguer

Peux-tu essayer d'ajouter ça à la fin de ton `~/.minemacs.d/modules.el`, 

```elisp
(setq minemacs-disabled-packages
      (append minemacs-disabled-packages
              '(me-org-extras
                org-contrib
                engrave-faces
                ox-hugo
                ox-extra
                org-modern
                org-fragtog
                evil-org
                evil-org-agenda
                org-contrib)))
```

Cela va désactiver packages tieces en relation avec Org mode histoire de voir si ça vient d'un entre eux. Si ça règle le problème, tu peux procéder à enlever un package à la fois et voir si Emacs se freeze de nouveau.

## Pour info!
Je pense que ça doit être un problème particulier sous Windows, car j'utilise Org d'une manière intense sous plusieurs machines Linux et je n'ai jamais eu de tel problème!

**Comment by raylemon** [comment]
Ça arrrive sur n’importe quel fichier org. Au mieux, ça crashe et ça ferme le programme, au pire ça reste bloqué.
J’ai essayé en désactivant les paquets org, ça ne change rien.

J’ai essayé en supprimant totalement le dossier .minemacs, ça ne change rien non plus.

Je vais tout clean et réinstaller minemacs pour voir…

C’est possible que ce soie Windows, mais je surveille les mises à jour et je n’ai rien vu de particulier. Je songe à retourner sous Linux pour ne plus avoir de soucis :D

**Comment by abougouffa** [comment]
Si tu lances Emacs en mode débogue `emacs --debug-init` ça ne donne rien de plus ?

Je sais que c'est une question stupide, mais est-ce que tu as essayé d'appuyer `C-g` lorsque ça bloque ?

**Comment by raylemon** [comment]
Bon, ça refonctionne, après avoir réinstallé minemacs au complet… Je suppose qu’il s’agit d’une mauvaise compilation ou autre... Je me souviens qu’il a demandé un moment d’installer tree-sitter pour python, mais tree-sitter n’existe pas pour Windows… C’est peut-être ça qui a tout cassé…

**Comment by abougouffa** [comment]
Super, ça me rassure!

Ah OK, je ne savais pas qu'il n'y a pas de tree-sitter sous Windows (ou de moins, pas facilement installable). Si c'est le cas, je peux conditionner l'initialisation de `treesit-auto` selon si on est sur une machine Windows ou pas.

**Comment by raylemon** [comment]
Je sais pas si c’est lié, mais Emacs a de nouveau freeze quand j’ai compilé une grammaire de tree-sitter…
Tree-sitter semble fonctionner (en le mettant dans .emacs.d/local/tree-sitter), mais le freeze resurgit tout le temps (et plus que dans un fichier org…)

Je sais pas d’où ça peut venir, je vais tenter d’utiliser d’autres version d’emacs pour voir.

**Comment by abougouffa** [comment]
J'ai le même comportement sur Linux (concernant les grammaires installées qui sont détectées comme non installées par `treesit-auto-install-all`). Par contre, je n'ai pour l'instant pas de soucis de ce type liés à tree-sitter.
