### ISSUE TITLE
Enabling additional fonts

### ISSUE THREAD

**Issue by oatmealm** [abougouffa/minemacs#14]
Hi there... wanted to ask where would be the best to stick something like this (or a better idea) to make sure it's picked up in the correct order. I think If it's run before the theme loads it gets overridden...

```
(set-fontset-font t
                  'hebrew
                  (plist-get hebrew-fonts :variable-pitch-font-family))

(set-fontset-font t
                  'arabic
                  (plist-get arabic-fonts :variable-pitch-font-family))
```

**Comment by abougouffa** [comment]
Hello @oatmealm,

I didn't test language specific fonts before.

Concerning the order in which one should load fonts, in MinEmacs, the fonts and the theme are loaded after loading Emacs (in `emacs-startup-hook`), `+set-fonts` is called then `+load-theme`. I think that font specific customizations should go after `+set-fonts`.

I've just pushed a commit to add two hooks `minemacs-after-set-fonts-hook` and `minemacs-after-load-theme-hook`, you can your customizations to one of them and test if it solves your problem.

You can use something like this:

```elisp
(add-hook 
  'minemacs-after-set-fonts-hook
  (lambda ()
    (set-fontset-font t 'hebrew (plist-get hebrew-fonts :variable-pitch-font-family))
    (set-fontset-font t 'arabic (plist-get arabic-fonts :variable-pitch-font-family))))
```

**Comment by oatmealm** [comment]
Tested it and it seems to work for me. Thanks.
