### ISSUE TITLE
[BUG] Warning: ‘+spell-fu-register-dictionaries!’ is an obsolete

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#146]
hi @abougouffa 
i saw your commit  https://github.com/abougouffa/minemacs/commit/b2b62bbfd3c148ed47f5d8cd8cc128a3224e7f74
use jinx for spell checking instead of spell-fu
then got an Warning: ‘+spell-fu-register-dictionaries!’ is an obsolete
You may have forgotten to modify this https://github.com/abougouffa/minemacs/blob/main/skel/config.el#L129-L132

**Comment by abougouffa** [comment]
Yep, I need to update the example. Thanks @donneyluck
