### ISSUE TITLE
[BUG] Jinx compilation failed [Windows]

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#147]
**Describe the bug**
```elisp
gcc -I. -O2 -Wall -Wextra -fPIC -shared -o jinx-mod.dll jinx-mod.c -I/usr/include/enchant-2 -lenchant-2
jinx-mod.c:19:10: fatal error: enchant.h: No such file or directory
   19 | #include <enchant.h>
      |          ^~~~~~~~~~~
compilation terminated.
Jinx: Compilation of jinx-mod.dll failed
```

**Emacs version**
```elisp
GNU Emacs 29.1.90 (build 1, x86_64-w64-mingw32) of 2023-12-15 Windows version
```

**Checkup list**
- [X ] You've tested disabling your `config.el` using `MINEMACS_IGNORE_CONFIG_EL=1 emacs`?

**To Reproduce**
1. Start Emacs
2. Visit any file

**Expected behavior**
Compilation of jinx, I suppose (?)

**Backtrace**
none

**Screenshots**
none

**Additional context**
none

**Comment by jonathanwilner** [comment]
You need to have the headers for enchant that are appropriate for your
platform in order for that to compile that library.

**Comment by abougouffa** [comment]
@raylemon 
Thanks for reporting this. Yep, as @jonathanwilner said, Jinx will need the [enchant library](https://abiword.github.io/enchant/) to be installed.

I think I will fall back to `spell-fu` on Windows, otherwise, you would need to [manually install `libenchant`](https://github.com/minad/jinx?tab=readme-ov-file#installation) in order for this to compile.

**Comment by raylemon** [comment]
I have installed `libenchant` with msys… but it’s still fail

**Comment by raylemon** [comment]
Pour info, jinx fonctionne sous Windows. Avec MSYS, il faut installer libenchant, glib2 et les dictionnaires.
Seulement, ta mise à jour vient de le désactiver sous Windows ^^. Si ça t’intéresse, je peux t’expliquer comment j’ai fait sous Windows.

**Comment by abougouffa** [comment]
Ah, super! Je le réactive du coup!
