### ISSUE TITLE
display-line-numbers-mode very pervasive

### ISSUE THREAD

**Issue by oatmealm** [abougouffa/minemacs#15]
I can see that you're disabling `display-line-numbers-mode` via a writeroom hook, but as far as I can tell it's enabled in `org` by default... I'm not sure that's a desired behavior most of the time...

**Comment by abougouffa** [comment]
MinEmacs is an opinionated configuration, for my taste, I like to have line numbers on Org buffers, but I like to have a very minimalist UI for Writeroom mode, and I find line numbers not useful in Writeroom mode. It is just a personal preference.

If you prefer to hide line numbers in Org mode buffers, you can add something like this to your `config.el`:

```elisp
(with-eval-after-load 'org
  (add-hook 'org-mode-hook (lambda () (display-line-number-mode -1))))
```
