### ISSUE TITLE
[BUG] Bug with Corfu

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#150]
**Describe the bug**
```elisp
﻿Error running timer ‘corfu--auto-complete-deferred’: (error "ispell-lookup-words: No plain word-list found at systemdefault locations.  Customize ‘ispell-alternate-dictionary’ to set yours.") [3 times]
```
I use ```jinx```, so, why it ask that ?

**Emacs version**
Run `M-x emacs-version` and put its output here:

```elisp
GNU Emacs 30.0.50 (build 1, x86_64-w64-mingw32)
```

**Checkup list**
- [X ] You've tested disabling your `config.el` using `MINEMACS_IGNORE_CONFIG_EL=1 emacs`?

**To Reproduce**
1. Open any file

**Expected behavior**

**Backtrace**
None

**Screenshots**

None

**Additional context**
None

**Comment by abougouffa** [comment]
Thanks for reporting this,

I didn't manage to reproduce this problem on Linux. Can you provide more details (a backtrace or more logs).

**Comment by raylemon** [comment]
I’m on previous commit (85008d70c3e1467e79c6039e83d5051c36724401) 
I can’t provide any backtrace or log, the only message I have is ```Error running timer ‘corfu--auto-complete-deferred’: (error "ispell-lookup-words: No plain word-list found at systemdefault locations.  Customize ‘ispell-alternate-dictionary’ to set yours.") [3 times]
```
At start, I see ```[Minemacs:LoadError] (void variable comp-async-buffer-name)

**Comment by abougouffa** [comment]
@raylemon 

The `(void-variable comp-async-buffer-name)` error seems to be related to Emacs 30. I will push a fix later.

I think the `ispell` issue is related to `cape-dict` not `spell-fu`. Can you try to put this in your config.el and see if it fixes the issue ?

```elisp
(with-eval-after-load 'cape 
  (remove-hook 'completion-at-point-functions 'cape-dict))
```

**Comment by raylemon** [comment]
With your code, it’s work fine.

**Comment by abougouffa** [comment]
@raylemon Thanks for the feedback, I will disable it by default as I'm not really using it!

**Comment by raylemon** [comment]
Update: when I have tested your code, I have not opened any file. So, this error remains : ```﻿Error running timer ‘corfu--auto-complete-deferred’: (error "ispell-lookup-words: No plain word-list found at systemdefault locations.  Customize ‘ispell-alternate-dictionary’ to set yours.")
```
This message are shown every times a press any key…

**Comment by abougouffa** [comment]
Can you test again please ? @raylemon

**Comment by raylemon** [comment]
With last commit (ed2bae5), this error still remains
```elisp
﻿Error running timer ‘corfu--auto-complete-deferred’: (error "ispell-lookup-words: No plain word-list found at systemdefault locations.  Customize ‘ispell-alternate-dictionary’ to set yours.")
```

**Comment by abougouffa** [comment]
To be sure we are using the same package versions, please run `M-x minemacs-update-restore-locked`. Wait for it to finish, then restart Emacs (maybe you need to wait a little bit for it to rebuild updated packages).

Then if you can try to run `MINEMACS_DEBUG=1 emacs` (or something similar on Windows, you need to set the environment variable `MINEMACS_DEBUG`. This way we might catch a traceback of the error.

**Comment by abougouffa** [comment]
@raylemon 

I suspect also this to be caused by some old custom variable in `~/.minemacs.d/custom-vars.el`, can you check if this file contains some `ispell` related config?

**Comment by raylemon** [comment]
I have this in custom-vars
```elisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ignored-local-variable-values '((org-export-in-background)))
 '(safe-local-variable-values
   '((eglot-workspace-configuration . eglot-ltex-workspace-config-fn))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "Cascadia Code" :height 120 :weight semi-light))))
 '(fixed-pitch ((t (:inherit default))))
 '(fixed-pitch-serif ((t (:inherit default))))
 '(mode-line ((t (:family "Lato" :weight regular))))
 '(mode-line-inactive ((t (:family "Lato" :weight regular))))
 '(variable-pitch ((t (:family "Lato")))))
```

**Comment by abougouffa** [comment]
Well it seems clean!

@raylemon Did you run these steps ?

> To be sure we are using the same package versions, please run `M-x minemacs-update-restore-locked`. Wait for it to finish, then restart Emacs (maybe you need to wait a little bit for it to rebuild updated packages).
> 
> Then if you can try to run `MINEMACS_DEBUG=1 emacs` (or something similar on Windows, you need to set the environment variable `MINEMACS_DEBUG`. This way we might catch a traceback of the error.

**Comment by raylemon** [comment]
I’ll do this now.

**Comment by raylemon** [comment]
Error still remains
```elisp
Debugger entered--Lisp error: (error "ispell-lookup-words: No plain word-list found at systemdefault locations. Customize 'ispell-alternate-dictionary’ to set yours.")
(error "ispell-lookup-words: No plain word-list found at systemdefault locations. Customize ’ispell-alternate-dictionary’ to set yours.")
ispell-lookup-words("title")
ispell-completion-at-point()
corfu-capf-wrapper(ispell-complation-at-point)
run-hook-wrapped(cofu--capf-wrapper ispell-completion-at-point)
corfu--auto-complete-deferred((#<window 3 on slides-intro.typ> #<buffer slides-intro.typ> 818 6419))
apply(corfu--auto-complete-deferred((#<window 3 on slides-intro.typ> #<buffer slides-intro.typ> 818 6419))
timer-event-handler([t 26013 54030 251719 nil corfu--auto-complete-deferred((#<window 3 on slides-intro.typ> #<buffer slides-intro.typ> 818 6419)) nil 0 nil ])
```

**Comment by abougouffa** [comment]
I see now.

The issue seems to be related to `ispell-completion-at-point` **which is a new feature** in Emacs **30.0.50**.

I stopped using Emacs 30 for my daily work because it is unstable, at least, when taking into account that third party packages used in MinEmacs doesn't support Emacs 30 yet.

I highly recommend to use Emacs 29 instead (in my machines, I always compile the latest commit in `emacs-29` branch.

**Comment by abougouffa** [comment]
@raylemon

You can try to temporary ignore errors in `ispell-completion-at-point` _(until you compile Emacs 29 for example)_ by dropping this in your config.el

```elisp
(with-eval-after-load 'ispell
  (advice-add 'ispell-completion-at-point :around (lambda (origfn &rest args) (ignore-errors (apply origfn args)))))
```

**Comment by raylemon** [comment]
I have both emacs 30 and emacs 29. v30 seems faster than v29, but I’ll wait for some stability. Thanks !
