### ISSUE TITLE
[BUG] tramp cannot be installed correctly

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#161]
emacs 29.1   
run     MINEMACS_DEBUG=1 emacs 
​​
![image](https://github.com/abougouffa/minemacs/assets/122257591/ee51f16f-e314-4f41-993e-abecf3568a2f)

**Comment by donneyluck** [comment]
I recompiled locally and installed 29.3 and the problem was solved

**Comment by stormwatch** [comment]
Hi @donneyluck!

May I bother you with the detailed steps of your workaround? Did you run `make` inside the tramp repo downloaded by straight? Will it work if my emacs version is 29.1?

Thanks
