### ISSUE TITLE
[BUG] two package  devdocs     

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#163]
![image](https://github.com/abougouffa/minemacs/assets/122257591/3a9444d7-8644-4af6-8305-7b1ae23e5633)
two package  devdocs    Will cause startup error
maybe need delete one of them

**Comment by abougouffa** [comment]
Hi @donneyluck ,

The skel/config.el is just an example of how to configure MinEmacs, **it is not intended to be loaded as it is**.

https://github.com/abougouffa/minemacs/blob/7263cdc7f9bd0e33d996f13681dfcd001e7cdc87/skel/config.el#L5-L10

**Comment by donneyluck** [comment]
I understand that when users copy your skel/* into .minemacs.d, the two devdocs will conflict, and it just so happens that some people don't understand how it works.
