### ISSUE TITLE
Rename light-dashboard to enlight

### ISSUE THREAD

**Issue by ichernyshovvv** [abougouffa/minemacs#168]
Hi. I saw you added light-dashboard to your emacs distro. We've changed the name of it and applied some changes to API (also, the updated version has much simpler defaults), so if you are still going to use it, fix the use-package declaration.

https://github.com/ichernyshovvv/enlight

**Comment by abougouffa** [comment]
Hello @ichernyshovv,

Thank you for letting me know! and thanks for the package by the way!
