### ISSUE TITLE
Unable to find theme file for ‘use-package’ when minemacs-theme is not set

### ISSUE THREAD

**Issue by oatmealm** [abougouffa/minemacs#17]
While I was trying to adapt my config to load a theme with `darkman.el` I've noticed I can't delay setting `minemacs-theme` or not set it at all and let `darkman` control the loading.

Not sure if that's an issue but it looks like `minemacs` will not finish loading unless `minemacs-tehem` is not `nil`.

```
Unable to find theme file for ‘use-package’
```

**Comment by abougouffa** [comment]
Can you please share the problematic snippet so I can see what's going wrong.

In general, you should enable the `darkman-mode` lately (after `minemacs-loaded`).

**Comment by abougouffa** [comment]
Can I consider this as resolved @oatmealm ?

**Comment by oatmealm** [comment]
Hi. Didn't have time to test it again I'm afraid. Will report if I'm still seeing this.
