### ISSUE TITLE
enlight now works in Emacs 27

### ISSUE THREAD

**Issue by ichernyshovvv** [abougouffa/minemacs#171]
Hi

Enlight now should work with at least Emacs 27, I've put compat to requirements.

But it does not work with evil-mode. I made a note for evil users in the [README](https://github.com/ichernyshovvv/enlight?tab=readme-ov-file#for-evil-users)

**Comment by abougouffa** [comment]
Thanks for letting me know @ichernyshovvv 

MinEmacs doesn't support Emacs 27. So, I wouldn't be able to test it.

Evil support wouldn't be difficult to add, it just consists of binding the keys (mapping `h`, `j`, `k`, `l` to `left`, `down`, `up`, `right` and the menu keys in `evil-normal-state-map`).

Something like:

```elisp
(with-eval-after-load 'evil
  (keymap-set evil-normal-state-map "j" #'enlight-menu-forward-item)
  (keymap-set evil-normal-state-map "k" #'enlight-menu-backward-item)
  (keymap-set evil-normal-state-map "q" #'bury-buffer)

  ;; For each (key . def) in the menu, 
  (keymap-set evil-normal-state-map key def))
```

TBH, I'm moving away from Evil to a more mainstream Emacs experience. I'm experimenting with Meow for modal editing, which integrates better with Emacs default keybindings and is less intrusive than Evil.
