### ISSUE TITLE
[BUG] a fresh clone of minemacs on the minemacs-ng branch comes with a bunch of errors

### ISSUE THREAD

**Issue by reynard93** [abougouffa/minemacs#174]
**Describe the bug**
Starting up Emacs brings up a bunch of errors

**Emacs version**
Run `M-x emacs-version` and put its output here: BNU Emacs 29.1 x86_64 apple-darwin

```elisp
;;
GNU Emacs 29.1 (build 1, x86_64-apple-darwin23.4.0, Carbon Version 170 AppKit 2487.5)
```

**Checkup list**
- [x] You've tested disabling your `config.el` using `MINEMACS_IGNORE_CONFIG_EL=1 emacs`?

**To Reproduce**
1. git clone the repo and switch to the minemacs-ng branch
2. start up emacs
3. See error

**Expected behavior**
Errors would be seen on *messages*

**Backtrace**
If the bug rises an error, please attach the full backtrace. To be sure to obtain a backtrace, you should launch Emacs with `MINEMACS_DEBUG=1 emacs` or `emacs --debug-init`.

```elisp
;; Put the backtrace here!
```
[MinEmacs:LoadError] (error Failed to run "git"; see buffer *straight-process*)
[MinEmacs:Error] Cannot load theme doom-one-light, trying to load the default theme doom-one-light
[MinEmacs:Error] Cannot load default theme doom-one-light, falling back to the builtin tsdh-light theme
save-current-buffer: Symbol’s function definition is void: satch-add-hook
Mark set
<nil> <down-mouse-1> is undefined
<nil> <mouse-1> is undefined
<left-fringe> <mouse-1> is undefined [2 times]
Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 

Invalid choice.  Suppress `use-package' warnings?  (yes, ignore `use-package' warnings completely, no, just disable showing them, quit and do nothing, ?): 
**Screenshots**
![image](https://github.com/abougouffa/minemacs/assets/32264460/b94556f4-2fb1-416c-8f79-171f2db6a933)

**Additional context**

**Comment by abougouffa** [comment]
Thank you for the feedback!

Interesting, it seems to be related to `straight.el`! I will try to take a look into it

**Comment by abougouffa** [comment]
I've tried it on my machine and it works without issues.

I've seen a similar problem on the CI yesterday, the CI was failing with similar error. It seems to be related to the NonGNU ELPA repository (maybe it wasn't accessible). I have rerun the CI without any modification to the code and now it passes.

You can try again as it seems that the server is accessible now.

**Comment by reynard93** [comment]
Hi @abougouffa thanks for looking into it, it is working now !
