### ISSUE TITLE
Windows - Error after loading

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#2]
Hello again!

I want to use minemacs with org and ltex, but not sucessfull… After an update, I have this strange message at start:

`Symbol’s` definition is void: get-scratch-buffer-create`

![emacs206](https://user-images.githubusercontent.com/5302343/210070302-4fb061af-c81b-42ad-ae1f-ada184456e5c.png)

How I can fix that ?

(emacs 28 on windows - reverting to emacs 28 due to some bugs with emacs 29 and 30)

Thanks !

**Comment by abougouffa** [comment]
Thanks for reporting it, should be fixed now!
