### ISSUE TITLE
How to shorten the startup time

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#20]
doom start less then 1s

your config start over 10s on macos & manjaro

what can i do to speed up

**Comment by abougouffa** [comment]
Hello,

In my machine, my MinEmacs config starts in less than 2s with almost all modules enabled (I have a pretty fast machine though). The `evil` package is causing most of the load time and blocking Emacs for a while on startup, I tried to figure out why but without success.

MinEmacs uses `use-package` and `with-eval-after-load` to defer loading packages. If you've added some customizations in your `~/.minemacs.d/config.el`, make sure you do not load any package with `load` or `require`, and use `use-package` and `with-eval-after-load` as in the provided example.

I will leave this open to investigate the `evil` issue later.

**Comment by abougouffa** [comment]
I will try to rewrite some parts of the config later, I remember in the beginning I had a pretty fast setup (starts in less than 0.5s with all stuff enabled). However, I think I messed it up at some point.

**Comment by abougouffa** [comment]
@donneyluck Can you please launch Emacs from terminal with `MINEMACS_VERBOSE=1', then after loading Emacs type `SPC b M` to open `*Messages*` buffer and share it content.

This will help me see which package is taking an abnormal init time (I suspect `evil` to do so).

**Comment by abougouffa** [comment]
I've refactored the MinEmacs code (specially for `general`) to speedup startup. Now, Emacs loads in 0.2s in my machine. The problem was caused by `general`'s keybinding definers.

@donneyluck Can you test the last version and see if it solves your problem?

**Comment by donneyluck** [comment]
ok  let me test it  wait a sec

**Comment by abougouffa** [comment]
Thank you for testing.
