### ISSUE TITLE
how to select region fast 

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#23]
hi.   can you tell me in your workflow 
how to fast select region in minemacs
if you just use evil  virsual-mode 
you can see this https://github.com/redguardtoo/emacs.d/blob/e6972bc35ba1b1df1fa5855845033c5e3f7bd860/lisp/init-evil.el#L422
very fast way with expand-region

**Comment by abougouffa** [comment]
Good idea! I've added `expand-region` to `me-extra`, I will test it and push the changes soon. Thank you for the inspiration!

**Comment by abougouffa** [comment]
Added in c5b1070aac4a8748018f705eae76268fb07b0a4c
