### ISSUE TITLE
suggest  about  consult-line & consult-ripgrep

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#25]
when SPC s s or  SPC s l
can not use thing-at-point or use select region
I found some solutions
https://emacs-china.org/uploads/default/original/2X/f/f522a8faeb8046136dc4830d49ac646c528d15c1.gif

default use thing-at-point and if you press any thing will delete default  use your input 

code is here  

https://github.com/lynnux/.emacs.d/blob/ac552c1/settings/package_extra.el#L1225-L1299

So please check whether it is added to the framework

**Comment by abougouffa** [comment]
Hello @donneyluck,

I like the idea of using `thing-at-point` as an initial input for `consult-ripgrep` and `consult-line`.

The code above seems an overkill for this, and it uses `ivy`, so I would need to adapt it or find another way to implement this. I will keep this issue open until I implement this.

Thank you for the suggestion, I really appreciate it!

**Comment by abougouffa** [comment]
I've just pushed a commit (97d48069c6e6daf73d84a8921090a888a57350eb) which advices `consult-line`, `consult-man`, `consult-grep`, ``consult-ripgrep`` and ``consult-find`` to implement the requested feature (that I like).

Try now to invoke one of the commands above from some place, and the query will be automatically filled depending on the current point (DWIM style).

If a region is selected, it will be used, otherwise, it will check for the symbol, string, email, number or word at point (in this order, see ``+region-or-thing-at-point``).

**Comment by donneyluck** [comment]
Hello @abougouffa  Thank you very much for your commit

the suggest is not only use the thing-at-point

use thing-at-point is a simple solution

https://github.com/lynnux/.emacs.d/blob/ac552c1/settings/package_extra.el#L1225-L1299

this solution can do more

The default behavior is to use thing-at-point and selected it at minibuffer 

then your can C-j C-k what you want

if you want some thing else  you just input some key     

the selected old（thing-at-point）will be delete automaticly

your commit just do 1 step

I wonder if you understand what I mean ？

**Comment by abougouffa** [comment]
Hi @donneyluck , Yep, now I understand better.

However, I don't really like the too automated stuff, for example, I can expect, in many cases, I would want to keep the input filled from `thing-at-point` and add some extra string to it. And if I want to delete the inserted text, I can simply press `C-M-<backspace>` one or two times!

For example, if I'm in a buffer containing:

```
This is some text.
Line one contains this value| 100,
Line two contains this value 101.
Line three contains this value 102.
...
And this line contains the value 200.
```

Supposing the cursor is in the first occurrence of the word `value`. I can press `SPC b l` to run `consult-line`. It starts with `value` as input, I type ` 200` to directly jump to the line containing `value 200`.

For my workflow, the current setup is more than enough.

**Comment by donneyluck** [comment]
After thinking
I agree with you
step2 maybe do to mush
the current setup is more than enough
thks

**Comment by donneyluck** [comment]
I tested it
there  have a small problem
when select region and press SPC S    command consult
when your c-j  c-k  move to what you want   press ret
the select region not quit
maybe  need add hook  to  minibuffer-hook   to  cancel selected

**Comment by abougouffa** [comment]
Good point! I've pushed a fix for that thanks.
