### ISSUE TITLE
Symbol's function definition is void: string-join

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#27]
![image](https://user-images.githubusercontent.com/122257591/223616575-3c6fdaf2-a1f2-40fe-b540-cf874b85e753.png)

crashed when start emacs
emacs28.2 
manjaro last commit

**Comment by abougouffa** [comment]
Ops, sorry for the inconvenience. I will push a fix!

**Comment by donneyluck** [comment]
thks :)
