### ISSUE TITLE
Wrong type argument:  sequencep, t

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#28]
Wrong type argument:  sequencep, t
ops crashed again
manjaro last commit
emacs 28.2

**Comment by donneyluck** [comment]
![image](https://user-images.githubusercontent.com/122257591/223913999-4cde2a80-1fe6-4057-b5a4-1048ba3f1f66.png)
anthor error

**Comment by donneyluck** [comment]
![image](https://user-images.githubusercontent.com/122257591/223915368-dce0a4b5-0526-41f0-a8ae-14ac394e4f22.png)

**Comment by abougouffa** [comment]
Hello @donneyluck,

Thank you for reporting this, I will take a look at it ASAP.

**Comment by donneyluck** [comment]
sorry maybe my mistake.  make cleanall. already solved

**Comment by donneyluck** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/122257591/224053414-6a17e929-8865-4109-941a-ef4ab6483935.png">
this problem still exists

**Comment by donneyluck** [comment]
sorry i test again no error

**Comment by abougouffa** [comment]
Hello @donneyluck ,

Yesterday's last commit should fix this, can you please `git pull origin main` and try again!

**Comment by donneyluck** [comment]
thks already pull  fix it.

**Comment by donneyluck** [comment]
everything is ok   on my  macos

but on manjaro linux            

Wrong type argument: sequencep, t       


![image](https://user-images.githubusercontent.com/122257591/224206579-71131647-2f02-48f4-b879-46111cbf51ac.png)

**Comment by donneyluck** [comment]
i have build emacs 30.0.5 on my manjaro  
then start everything is ok

**Comment by donneyluck** [comment]
can you tell me your build  compile parameters
like this 
```
./configure --with-native-compilation=no   # native-comp 有需要可开启 
--with-tree-sitter 
--with-cairo 
--with-imagemagick # 可选依赖，参考 10L
CFLAGS="-O2 -pipe -march=native" 
--without-pop 
--with-pgtk # 如果是 wayland 开启，否则删除本行
```

**Comment by abougouffa** [comment]
This seems to be a `straight.el` problem, I was using the `develop` branch in MinEmacs, which is not stable, the last commit switch back to the `master` branch which hopefully do not have this issue.

I'm using Manjaro Linux too, I'm using a slightly modified version of the `emacs-git` AUR recipe. The `system-configuration-options` variable in my installation evaluates to:

```elisp
"--prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --mandir=/usr/share/man --with-gameuser=:games --with-modules --without-libotf --without-m17n-flt --without-gconf 'CFLAGS=-march=native -mtune=native -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection' --enable-autodepend --with-native-compilation=yes --with-native-compilation=aot --with-xinput2 --with-sound=alsa --with-xwidgets --with-tree-sitter --without-compress-install '--program-transform-name=s/\\([ec]tags\\)/\\1.emacs/' LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
```

**Comment by donneyluck** [comment]
thanks everything ok
