### ISSUE TITLE
evil-escape can not escape from iedit & evil-mc

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#30]
hi @abougouffa 
after my test   evil-escape  **kj** or **fd** can not escape from evil-iedit-state  &  evil-mc
so maybe need support it
thks

**Comment by abougouffa** [comment]
Hello @donneyluck ,

The `evil-iedit-state` is supported by `evil-escape`, the current MinEmacs config leaves the `C-;` bound to `iedit-mode`. I will change it to `evil-iedit-state/iedit-mode` instead, this should solve the issue for `iedit`.

However, for `evil-mc`, I don't know how to integrate it efficiently with `evil-escape`. Feel free to share a solution if you found one!

**PS:** I'm changing the `evil-escape-key-sequence` to `"kj"` like you've suggested before https://github.com/abougouffa/minemacs/pull/21/commits/0cf430e8d2d1b145884371d08d47fc939f8f640b. It makes more sens than `"fd"` which interferes with `evil-find` or `evil-snipe-f`.

**Comment by donneyluck** [comment]
thank you for your time
