### ISSUE TITLE
can`t org-export-html

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#32]
hi @abougouffa 
after my test  minemacs can`t org export html
i have create a simple file  test.org  then  press   SPC m e h h 

![image](https://user-images.githubusercontent.com/122257591/225554476-bd453636-4104-47b8-a8ff-0598f6a1c24c.png)

i have read FAQ and add code in config.el

```
(with-eval-after-load 'org
  (setq org-export-in-background nil))

(with-eval-after-load 'org
  ;; You can also set it to your own custom init.el, just do not forget to
  ;; provide `me-org-export-async-init' in it.
  (setq org-export-async-init-file nil))

```

still not work   
Looks a bit complicated from my beginner's perspective, maybe it needs to be simplified

**Comment by abougouffa** [comment]
I've just tested it with the `README.org` file of this repository, in my machine the export runs OK (with `org-html-export-to-html` or `org-html-export-as-html`).

After adding this to your `config.el`, can you tell me what error Emacs is signaling?

```elisp
(with-eval-after-load 'org
  (setq org-export-in-background nil
        ;; You can also set it to your own custom init.el, just do not forget to
        ;; provide `me-org-export-async-init' in it.
        org-export-async-init-file nil))
```

**Comment by donneyluck** [comment]
My son is sick, so may have to take the test again later 

When I test it, I will updating this issues

**Comment by donneyluck** [comment]
hi @abougouffa  i have test it again
try to export README.org
work well 
but it take 10s   is this normal？

**Comment by abougouffa** [comment]
It depends on the machine and the file, but for an export to HTML it should be quite fast.

**Comment by donneyluck** [comment]
ok I will continue to pay attention to this
