### ISSUE TITLE
unicode-font got error

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#38]
![image](https://user-images.githubusercontent.com/122257591/227481249-f5da3585-5286-42ab-8325-96c9d22bbb02.png)

emacs 30.0.50 native-comp
manjaro linux

**Comment by abougouffa** [comment]
It seems to be an Emacs issue https://github.com/emacs-mirror/emacs/commit/263d6c38539691c954f4c3057cbe8d5468499b91#commitcomment-105809455

**Comment by donneyluck** [comment]
thks : )
