### ISSUE TITLE
how to use this pacakge

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#39]
i have add this config on my ~/.minemacs.d/config.el
```
(use-package screenshot
  :straight (:host github :repo "donneyluck/screenshot")
  :config (setq screenshot-upload-fn "upload %s 2>/dev/null"))
```

when start emacs  press M-x 
there is no function screenshot 
i have read the source code screenshot.el
function screenshot is an autoload function 
i don`t elisp how to load package. 
so realy need your help  
thanks for your time

**Comment by abougouffa** [comment]
Hello @donneyluck,

I've added the same snippet in my `~/.minemacs.d/config.el` and I've got the desired behavior:

![Screenshot_20230329_163109](https://user-images.githubusercontent.com/3716399/228572015-a718c5a5-ff0d-4fff-a2f4-b5ea90ec24b1.png)

Try to launch Emacs with `MINEMACS_DEBUG=1 emacs`, maybe there is an issue in your `config.el` and it is failing silently.

**Comment by donneyluck** [comment]
ok thanks i will try it later
