### ISSUE TITLE
Error in the definition of the Mu4e context

### ISSUE THREAD

**Issue by DarkBuffalo** [abougouffa/minemacs#43]
Hi @abougouffa ,
First of all very nice work

When we enter the context in the config.el file with +mu4e-register-account
example:
``` emacs-lisp
(+mu4e-register-account
   "Mon compte" ;; Account name
   ".mails" ;; Maildir
...)
```

mu4e defines the maildir folder as: /home/user/~/.mails

**Comment by abougouffa** [comment]
Hello @DarkBuffalo, thanks for the compliment!

Seems wired! did you initialize `mu init --maildir=/path/to/your/maildir` with your own maildir?

**Comment by DarkBuffalo** [comment]
> Hello @DarkBuffalo, thanks for the compliment!
> 
> Seems wired! did you initialize `mu init --maildir=/path/to/your/maildir` with your own maildir?


I did not put the absolute path
Now It works
Thanks
