### ISSUE TITLE
abot font set

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#50]
```
  minemacs-fonts
  '(:font-family "Noto Sans CJK SC"
    :font-size 13
    :variable-pitch-font-family "IBM Plex Serif"
    :variable-pitch-font-size 13))
```
i have set minemacs-font to Noto Sans CJK SC
but when input chinese   not use this font 
![image](https://user-images.githubusercontent.com/122257591/232025770-d19b7bd5-592b-4041-bc04-8a30e77ce2d4.png)

the font Noto Sans CJK SC  is monospaced font

**Comment by donneyluck** [comment]
https://github.com/abougouffa/minemacs/blob/main/elisp/%2Bminemacs.el#L82


http://xahlee.info/emacs/emacs/emacs_list_and_set_font.html

Maybe you can refer to xahlee's font setting method

Can be set separately  

Font for Unicode Symbols
Font for emoji
Font for Chinese

**Comment by abougouffa** [comment]
> Can be set separately
>
> Font for Unicode Symbols
> Font for emoji
> Font for Chinese

My previous comment talks about this. In my config, I use `unicode-fonts`. This package defines a set of fonts to use for the different Unicode blocks (Emoji, Arabic, Hebrew, CJK, ...).

Even if you manage to set the fonts separately outside, `unicode-fonts` will override them. Unless you customize the `unicode-fonts-block-font-mapping`. 

For me, I don't use other languages in my Emacs config, so I'm not interested to implement complex font configuration that I never use!

**Comment by donneyluck** [comment]
ok thanks again

**Comment by abougouffa** [comment]
@donneyluck Take a look on my comment edit! It might beuseful
