### ISSUE TITLE
mu4e-config questions: Can't quite get org-msg compose or mu4e-account-register functions working with mu4e

### ISSUE THREAD

**Issue by jonathanwilner** [abougouffa/minemacs#52]
Hi,

I'm typically a notmuch user for years, after originally starting with mu4e. I've got both working with minemacs, which is fantastic - thank you !

I used the skel files to get started with mu4e.

I have org-msg working great with notmuch using minemacs, with the composer/signature on by default. The only trouble I have is with gnus-alias not working, which is OK.  I just can't figure out how to get it working by default with new message composition in mu4e. The mode is active, but I have to switch to org-msg-edit in the body each time - and the signature isn't coming through.

I'm also trying to load the mu4e-account-register function when minemacs starts in order to manage multiple accounts. I get a void-function error I can't seem to diagnose. I think it might be the loading order, but would love a pointer in the right direction to try to get this working. Any ideas would be really appreciated !

Thanks again for publishing this. I realize it's mainly for your own use & you aren't trying to do a ton of technical support for others!

**Comment by abougouffa** [comment]
Hello @jonathanwilner ,

Happy to hear that you've found my config useful!

For the `+mu4e-register-account` part, you need to call it in a `(with-eval-after-load 'mu4e)` block in your config. I can make it `autoload` but I prefer leaving it like this, so I force my self to use deferred configuration to make Emacs loads faster.

For the `gnus-alias`, I really have no idea! I didn't hear about this package before. I remember that I've tried in the past to do something similar, `mu4e` provides `mu4e-compose-context-switch` but it doesn't work with `org-msg`.

In my workflow, I have a hook to `mu4e-compose-pre-hook` (defined in `me-mu4e-extras`) that checks if several aliases exist (aliases are configured in a per-account basis in `+mu4e-register-account`) and propose completion to select which account to use. The current tweak doesn't use separate signatures for each alias, but it can easily be modified to do so.

Sorry if this didn't answer your question! I've taken a look on the `gnus-alias` package, but with `mu4e` being `mu4e`, I think it will take me a decade before figuring out how to make it work with `gnus-alias`!
