### ISSUE TITLE
Dirvish produces "error in process sentinel : end of file while parsing"

### ISSUE THREAD

**Issue by jonathanwilner** [abougouffa/minemacs#53]
I've always gotten "error in process sentinel : end of file while parsing" when opening a new directory, which looks like an error from Dirvish. 

error in process sentinel: dirvish-dir-data-proc-s: End of file during parsing
error in process sentinel: End of file during parsing

**Comment by abougouffa** [comment]
Hello @jonathanwilner ,

Thank you for bringing this to my attention;

I can't reproduce it on my machine. Can you please enable debugging `SPC t d` before launching the command which triggers the issue? 

Or, more simply, you can start Emacs with:

```shell
MINEMACS_DEBUG=1 emacs
```

And share the backtrace and mention which Emacs version you are using. These can help me track the issue down.

**Comment by jonathanwilner** [comment]
Hi - it's not generating a backtrace at all. :-( 

I'm getting a bunch of blank output from Dirvish / Dirvish-preview. Here's the screenshot from the buffers it creates. 

<img width="857" alt="Screenshot 2023-04-23 at 9 39 35 AM" src="https://user-images.githubusercontent.com/4776967/233852673-7a8dcd69-5da6-4f5c-931f-b5cf3fe9599a.png">

Emacs is : 
GNU Emacs 30.0.50 (build 1, aarch64-apple-darwin22.4.0, NS appkit-2299.50

**Comment by abougouffa** [comment]
Dirvish do create some temporary buffers while generating previews. These should not cause a problem.

I've tested it on my machine, but I can't reproduce a similar behavior! I don't have access to a Mac machine, so I can't test in the exact same conditions.

One caveat though, I've moved to Emacs 29.0.90 for the moment. The last time I've used Emacs 30.0.50 I've noticed some wired messages (not related to `dirvish`, I didn't try `dirvish` on Emacs 30 from a while).

In all cases, I think that this issue should be reported to [`dirvish`](https://github.com/alexluigit/dirvish)'s developers, specially if you can reproduce it in a minimal setup (using `emacs -Q`). You can try something like this `dirvish-minimal.el`:

```elisp
;; Install
(package-vc-install "https://github.com/alexluigit/dirvish")

;; Use
(use-package dirvish
  :hook (emacs-startup . dirvish-override-dired-mode)
  :custom
  (dirvish-attributes '(subtree-state all-the-icons file-size vc-state git-msg))
  (dirvish-mode-line-format '(:left (sort file-time symlink) :right (omit yank index)))
  (dirvish-side-width 30)
  (dirvish-fd-default-dir "~/")
  (dirvish-use-header-line t) ; 'global make header line span all panes
  (dirvish-use-mode-line t))
```

Then run this to try to reproduce the issue in a minimal setup.:

```shell
emacs -Q -l dirvish-minimal.el
```

**Comment by jonathanwilner** [comment]
It's a problem with Dirvish on MacOS. 

https://github.com/alexluigit/dirvish/pull/192
