### ISSUE TITLE
Cannot disable posframe?

### ISSUE THREAD

**Issue by jonathanwilner** [abougouffa/minemacs#54]
Hi,

Probably a silly question related to my own config, but I've hunted and hunted to find what changed re: completion using what looks like posframe. Is it actively enabled somewhere? I can't find anything that would indicate it's in use, including variables, but the completion sure looks like it's using it. Any tips appreciated or a quick - "that's on you!" would be great too. 

Thanks again for such an awesome configuration !

**Comment by abougouffa** [comment]
Hello @jonathanwilner ,

I'm not sure if I've understood your question. If you can provide a screenshot or a GIF, it would be helpful.

If you are looking for the package responsible for MinEmacs' completion in a child frame (the built-in feature used by `posframe`), it is `corfu`. There are 2 modes directly involved, `corfu-mode` and `corfu-popinfo-mode`:

![image](https://user-images.githubusercontent.com/3716399/234866291-f1caa042-04d2-419c-958d-9a782559aa62.png)

These are configured in `me-completion`. By default, `corfu-mode` is enabled globally. If you want to enable it only in some modes, let's say, `prog-mode`, you can add something like this to your config:

```elisp
(remove-hook 'minemacs-after-startup-hook #'global-corfu-mode)
(add-hook 'prog-mode-hook #'corfu-mode)
```

**Comment by abougouffa** [comment]
You can also leave `corfu` enabled globally and tweak the `corfu-exclude-modes` customization variable (for example, to exclude `org-mode`).

```elisp
(with-eval-after-load 'corfu
  (push 'org-mode corfu-exclude-modes))
```

**Comment by xanmodlouis** [comment]
i love this framework, thanks for your work!

**Comment by abougouffa** [comment]
Thanks @xanmodlouis , Happy you've found it useful!

**Comment by abougouffa** [comment]
@jonathanwilner did my comment answers your question?

**Comment by jonathanwilner** [comment]
Yes, it put me on the right track re corfu and corfu-terminal . Thank you !
