### ISSUE TITLE
prevent-org-source-block-face-from-bleeding-out-in-fold

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#58]
hi @abougouffa 
i have the same problem
https://emacs.stackexchange.com/questions/52324/prevent-org-source-block-face-from-bleeding-out-in-fold
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=52587  maybe a bug

my solution
```

(defun get-theme-background-color ()
  (cdr (assoc 'background-color (frame-parameters))))

(defun set-org-block-end-line-color ()
  "Set org-src-block face background color to current theme's background color."
  (interactive)
  (let ((background-color (get-theme-background-color))) ; 
    (set-face-attribute 'org-block-end-line nil :background background-color))) ; 

(advice-add 'consult-theme :after (lambda (&rest args) (set-org-block-end-line-color)))
```

This is just a suggestion, please join according to your preferences

**Comment by abougouffa** [comment]
In my experience, this does occur only when there is no empty line between the heading and the `#+end_src`. I would rather prefer to leave this behavior to remind me to add the missing new line.

**Comment by donneyluck** [comment]
but if there is an empty line between the heading and the #+end_src like this
![image](https://github.com/abougouffa/minemacs/assets/122257591/29e605e6-53e8-418c-97d4-0f66b3987087)
press tab can not unfold heading

**Comment by abougouffa** [comment]
> press tab can not unfold heading

Well, in my machine it does unfold it! @donneyluck 

I'm using Emacs 29 by the way, it is more stable than Emacs 30 nowadays

**Comment by donneyluck** [comment]
It should be noted that it is not after the title  press tab
Cursor needs to be behind   ↩   then press tab

**Comment by abougouffa** [comment]
> Cursor needs to be behind ￼ then press tab

In my machine, it unfolds in all cases!

> my solution

The code you provided overwrites the `#+end_src` background, which fixes the issue when the headings are folded, but when you unfold them, you can notice that the `#+end_src` has the wrong background.

![image](https://github.com/abougouffa/minemacs/assets/3716399/246e6739-433d-47c0-85bb-234281a82d0e)
