### ISSUE TITLE
Given parent class emacsql-sqlite-connection is not a class 

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#62]
hi  @abougouffa 
when first open magit  
here is the log 

Turning on magit-auto-revert-mode...done
Given parent class emacsql-sqlite-connection is not a class

**Comment by abougouffa** [comment]
See #49 

You can run `M-x minemacs-update` to fix it.

**Comment by donneyluck** [comment]
emacs 29.0.92 

I deleted the previous .emacs.d and re-cloned to ensure a clean environment

When all packages are installed and compiled

run `minemacs-update`

then` space g g`  

still have this problem
