### ISSUE TITLE
about modules/obsolete/me-yasnippet.el

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#63]
@abougouffa 
I found that in your config yasnippet is marked as obsolete 
In my impression this is a powerful code templating tool 
if this is obsolete I would like to know what package do you use to replace it in your workflow
thks

**Comment by abougouffa** [comment]
I'm using `tempel` instead of `yasnippet`. You can still use the obsolete `yasnippet` configuration by add the `obsolete/me-yasnippet` to `minemacs-modules`.
