### ISSUE TITLE
key conflict about org-roam

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#68]
hi @abougouffa 
1.
org-roam-node-random & org-roam-ui-open   use same key    `nR`
2.
I am using org-roam for the first time
I found it didn't work properly  eg:   `org-roam-node-find`
After investigation, it was found that it was not implemented    `org-roam-db-sync`
there maybe need a hook  after insert new roam node
3.
when first run org-ui-open  so many warning  and two window open
![image](https://github.com/abougouffa/minemacs/assets/122257591/449eb682-073f-4179-97c5-6b8bf0b2343d)

![image](https://github.com/abougouffa/minemacs/assets/122257591/f09f5d42-381f-4c71-ac92-d8f14c568d77)

**Comment by abougouffa** [comment]
Thank you for reporting this @donneyluck;

I will fix it soon!

**Comment by abougouffa** [comment]
Should be fixed by now!
