### ISSUE TITLE
Usability Questions

### ISSUE THREAD

**Issue by mandarvaze** [abougouffa/minemacs#7]
@abougouffa Didn't find `Discussions` hence asking as issue

1. Do you byte-compile the code like Doom emacs ? In my non-scientific testing, MinEmacs feels slower than Doom emacs
2. How can I `discover` the keybindings ? From Doom I was able to guess `SPC f f` to find file. But once I press `SPC` I don't see any hints (like Doom) e.g. I tried `SPC b d` to delete the buffer (From Doom) but it says `SPC b d is undefined`

**Comment by mandarvaze** [comment]
I found some keybindings in `core/me-keybindings.el`

**Comment by abougouffa** [comment]
1. For byte-compilation, the packages are byte (and native) compiled by `straight.el`. But the MinEmacs configuration files aren't.

2. The hint is provided via `which-key`, when you press `SPC`, it should show the available commands, `SPC f`, it shows the commands under `SPC f`... and so on. 

![Screenshot_20230127_231652](https://user-images.githubusercontent.com/3716399/215216222-db3b0352-108d-4635-8fd9-4b96fa83b20e.png)

MinEmacs is configured as follows:
- After 1s of hitting `SPC`, it shows the hint.
- After hitting `f` by 0.5s, it shows the files hint... and so on.

There is an issue which I've noticed but didn't find a way to fix when hitting `SPC f` (and many other commands) for the first time. It shows the hint for a breive moment and hides it. But after the second attempt, it should work correctly.
This is related to some mode keymap specific `general.el` bindings.

**Comment by mandarvaze** [comment]
@abougouffa Few moe questions (these may be coming because I'm coming from doom)

1. Is there an equivalent of `doom sync` ? (I think `make clean` will work)
2. When **must** we run `make clean` ?
3. I assume installing external packages is to be done by `M-x package-install` and there is no equivalent of `$MINEMACSDIR/packages,el`

**Comment by abougouffa** [comment]
Hello @mandarvaze ,

Nop, it is not an equivalent of `doom sync`, the Makefile in MinEmacs is quite simple, and can be useful sometimes when:
 - you want to clean the cache and the byte/native compiled files (`make clean`), 
 - or to clean all locally installed packages to force a reinstall of all packages the next time you run Emacs (`make clean_all`),
 - or remove the `.emacs.d/local/` directory (`make prune`).

For package installation, MinEmacs uses [`straight.el` and `use-package`](https://github.com/radian-software/straight.el#integration-with-use-package). There is no equivalent of Doom's `packages.el`. One of the reasons I stopped using Doom is this overhead. MinEmacs is just a vanilla Emacs with some customizations.

The best way to install packages is just to add the `use-package` declarations to your `config.el`, or if you want to separate your installed packages from the config file, you can create a file at `.minemacs.d/my-packages.el`, add the `use-package` declarations in it and load it from your `config.el` `(load "my-packages.el").

**Comment by oatmealm** [comment]
Right now it's "SPC w d"  do delete a window. If it goes by function name that's great, but as a functional mnemonic, maybe it's better to stick to either?
