### ISSUE TITLE
about editorconfig

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#72]
hi @abougouffa   after test
I found out that this function doesn't work properly
Executing under my Makefile
It will clear all tab indentation and cause the makefile to fail to run
![image](https://github.com/abougouffa/minemacs/assets/122257591/72353ed0-7b99-4017-9f30-fdf821996215)

This setting in make-mode causes this problem
![image](https://github.com/abougouffa/minemacs/assets/122257591/dbdf9a6c-6b11-4ff9-8819-2cc1a16cd05e)

**Comment by abougouffa** [comment]
Hello @donneyluck 

Thanks for reporting this. I will try to test it later.

However, this issue isn't MinEmacs', it should be reported in the editorconfig-emacs repo!
