### ISSUE TITLE
mu4e error

### ISSUE THREAD

**Issue by DarkBuffalo** [abougouffa/minemacs#74]
hi @abougouffa,

When you start MU4E, the following error is displayed:

`cl-generic-ensure-function: gnus-icalendar-event:opt-participants is already defined as something else than a generic function`

mu4e don't start

**Comment by abougouffa** [comment]
Hello @DarkBuffalo ,

This might be a `mu4e` issue (take a look in their repo). You can try to disable `mu4e-icalendar` by adding this in your `modules.el` file:

```elisp
(push 'mu4e-icalendar minemacs-disabled-packages)
```

**Comment by DarkBuffalo** [comment]
@abougouffa 
thanks

**Comment by DarkBuffalo** [comment]
Debugger entered--Lisp error: (error "gnus-icalendar-event:opt-participants is already d...")
  error("%s is already defined as something else than a gen..." gnus-icalendar-event:opt-participants)
  cl-generic-ensure-function(gnus-icalendar-event:opt-participants)
  cl-generic-define-method(gnus-icalendar-event:opt-participants nil ((this gnus-icalendar-event)) nil #f(compiled-function (this) "Retrieve the slot `opt-participants' from an object of class\n`gnus-icalendar-event'." #<bytecode 0x97c53491b02f2e2>))
  byte-code("\300\301\302\303!\"\210\300\304\305\303!\"\210\300\306\304\"\210\307\306\310\311#\210\312\303\313\304#\314\303\315\316\317$\210\320\321\315\322\315\323%\210\320\324\315\325\315..." [defalias gnus-icalendar-event-p eieio-make-class-predicate gnus-icalendar-event gnus-icalendar-event--eieio-childp eieio-make-child-predicate gnus-icalendar-event-child-p make-obsolete "use (cl-typep ... 'gnus-icalendar-event) instead" "25.1" define-symbol-prop cl-deftype-satisfies eieio-defclass-internal nil ((organizer :initarg :organizer :accessor gnus-icalendar-event:organizer :initform "" :type (or null string)) (summary :initarg :summary :accessor gnus-icalendar-event:summary :initform "" :type (or null string)) (description :initarg :description :accessor gnus-icalendar-event:description :initform "" :type (or null string)) (location :initarg :location :accessor gnus-icalendar-event:location :initform "" :type (or null string)) (start-time :initarg :start-time :accessor gnus-icalendar-event:start-time :initform "" :type (or null t)) (end-time :initarg :end-time :accessor gnus-icalendar-event:end-time :initform "" :type (or null t)) (recur :initarg :recur :accessor gnus-icalendar-event:recur :initform "" :type (or null string)) (uid :initarg :uid :accessor gnus-icalendar-event:uid :type string) (method :initarg :method :accessor gnus-icalendar-event:method :initform "PUBLISH" :type (or null string)) (rsvp :initarg :rsvp :accessor gnus-icalendar-event:rsvp :initform nil :type (or null boolean)) (participation-type :initarg :participation-type :accessor gnus-icalendar-event:participation-type :initform 'non-participant :type (or null t)) (req-participants :initarg :req-participants :accessor gnus-icalendar-event:req-participants :initform nil :type (or null t)) (opt-participants :initarg :opt-participants :accessor gnus-icalendar-event:opt-participants :initform nil :type (or null t))) (:documentation "Generic iCalendar Event class.") cl-generic-define-method gnus-icalendar-event:opt-participants ((this gnus-icalendar-event)) #f(compiled-function (this) "Retrieve the slot `opt-participants' from an object of class\n`gnus-icalendar-event'." #<bytecode 0x97c53491b02f2e2>) \(setf\ gnus-icalendar-event:opt-participants\) (value (this gnus-icalendar-event)) #f(compiled-function (value this) #<bytecode 0x1803029a93921902>) gnus-icalendar-event:req-participants ((this gnus-icalendar-event)) #f(compiled-function (this) "Retrieve the slot `req-participants' from an object of class\n`gnus-icalendar-event'." #<bytecode 0x97c53784efd27e2>) \(setf\ gnus-icalendar-event:req-participants\) (value (this gnus-icalendar-event)) #f(compiled-function (value this) #<bytecode 0x1803029a939238c2>) gnus-icalendar-event:participation-type ((this gnus-icalendar-event)) #f(compiled-function (this) "Retrieve the slot `participation-type' from an object of class\n`gnus-icalendar-event'." #<bytecode 0xbe3672486ad162a>) \(setf\ gnus-icalendar-event:participation-type\) (value (this gnus-icalendar-event)) #f(compiled-function (value this) #<bytecode 0x1803029a93920f82>) gnus-icalendar-event:rsvp ((this gnus-icalendar-event)) #f(compiled-function (this) "Retrieve the slot `rsvp' from an object of class\n`gnus-icalendar-event'." #<bytecode -0x148117b3e10b0b4a>) \(setf\ gnus-icalendar-event:rsvp\) (value (this gnus-icalendar-event)) #f(compiled-function (value this) #<bytecode 0x1803029a93921d42>) gnus-icalendar-event:method ((this gnus-icalendar-event)) #f(compiled-function (this) "Retrieve the slot `method' from an object of class\n`gnus-icalendar-event'." #<bytecode -0x22e45960ff5a7ba>) \(setf\ gnus-icalendar-event:method\) (value (this gnus-icalendar-event)) #f(compiled-function (value this) #<bytecode -0x17fa2c273d01c63e>) gnus-icalendar-event:uid ((this gnus-icalendar-event)) #f(compiled-function (this) "Retrieve the slot `uid' from an object of class\n`gnus-icalendar-event'." #<bytecode -0x11b42e188160d2b1>) ...] 7)
  require(gnus-icalendar)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\210\300\314!\210\300\315..." [require cl-lib cl-macs cl-seq gnus-art gnus-cite gnus-dired gnus-icalendar gnus-msg htmlize message mml org ox subr-x url-parse xml custom-declare-group org-msg nil "Org Message group." :group applications] 6)
  require(org-msg nil t)
  (not (require 'org-msg nil t))
  (if (not (require 'org-msg nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-msg) :error) (condition-case err (progn (eval-after-load 'me-general-ready #'(lambda nil (general-nvmap :keymaps 'org-msg-edit-mode-map "gg" #'org-msg-goto-body))) (eval-after-load 'me-general-ready #'(lambda nil (+minemacs--internal-map-local! :keymaps 'org-msg-edit-mode-map "a" '... "aa" #'org-msg-attach-attach "ad" #'org-msg-attach-delete "k" #'org-msg-edit-kill-buffer "p" #'org-msg-preview))) (org-msg-mode 1) t) ((debug error) (funcall use-package--warning190 :config err))))
  (progn (let ((custom--inhibit-theme-enable nil)) (if (memq 'use-package custom-known-themes) nil (custom-declare-theme 'use-package 'use-package-theme nil (list)) (enable-theme 'use-package) (setq custom-enabled-themes (remq 'use-package custom-enabled-themes))) (custom-theme-set-variables 'use-package '(org-msg-options "html-postamble:nil H:5 num:nil ^:{} toc:nil author..." nil nil "Customized with use-package org-msg") '(org-msg-startup "hidestars indent inlineimages" nil nil "Customized with use-package org-msg") '(org-msg-greeting-name-limit 3 nil nil "Customized with use-package org-msg") '(org-msg-convert-citation t nil nil "Customized with use-package org-msg") '(org-msg-default-alternatives '((new utf-8 html) (reply-to-text utf-8 html) (reply-to-html utf-8 html)) nil nil "Customized with use-package org-msg") '(org-msg-attached-file-reference (rx (or (seq "attach" ...) (seq "enclosed") (seq "attach" ... ... ...) (seq "ci" ... "joint" ...) (seq ... ... ... "joint" ... ...) (seq ...))) nil nil "Customized with use-package org-msg"))) (if (not (require 'org-msg nil t)) (display-warning 'use-package (format "Cannot load %s" 'org-msg) :error) (condition-case err (progn (eval-after-load 'me-general-ready #'(lambda nil (general-nvmap :keymaps ... "gg" ...))) (eval-after-load 'me-general-ready #'(lambda nil (+minemacs--internal-map-local! :keymaps ... "a" ... "aa" ... "ad" ... "k" ... "p" ...))) (org-msg-mode 1) t) ((debug error) (funcall use-package--warning190 :config err)))))
  (closure (t) nil (progn (let ((custom--inhibit-theme-enable nil)) (if (memq 'use-package custom-known-themes) nil (custom-declare-theme 'use-package 'use-package-theme nil (list)) (enable-theme 'use-package) (setq custom-enabled-themes (remq 'use-package custom-enabled-themes))) (custom-theme-set-variables 'use-package '(org-msg-options "html-postamble:nil H:5 num:nil ^:{} toc:nil author..." nil nil "Customized with use-package org-msg") '(org-msg-startup "hidestars indent inlineimages" nil nil "Customized with use-package org-msg") '(org-msg-greeting-name-limit 3 nil nil "Customized with use-package org-msg") '(org-msg-convert-citation t nil nil "Customized with use-package org-msg") '(org-msg-default-alternatives '(... ... ...) nil nil "Customized with use-package org-msg") '(org-msg-attached-file-reference (rx (or ... ... ... ... ... ...)) nil nil "Customized with use-package org-msg"))) (if (not (require 'org-msg nil t)) (display-warning 'use-package (format ```"Cannot load %s" 'org-msg) :error) (condition-case err (progn (eval-after-load 'me-general-ready #'(lambda nil ...)) (eval-after-load 'me-general-ready #'(lambda nil ...)) (org-msg-mode 1) t) ((debug error) (funcall use-package--warning190 :config err))))))()
  eval-after-load-helper("/usr/share/emacs/site-lisp/mu4e/mu4e.elc")
  do-after-load-evaluation("/usr/share/emacs/site-lisp/mu4e/mu4e.elc")
  mu4e--start(mu4e--main-view)
  mu4e(nil)
  funcall-interactively(mu4e nil)
  command-execute(mu4e record)
  execute-extended-command(nil "mu4e" nil)
  funcall-interactively(execute-extended-command nil "mu4e" nil)
  command-execute(execute-extended-command)```

**Comment by DarkBuffalo** [comment]
l'association des deux commandes suivantes supprimme le probleme:
``` elisp
(push 'mu4e-icalendar minemacs-disabled-packages)
(push 'org-msg minemacs-disabled-packages)
```

**Comment by abougouffa** [comment]
Quelle version de `mu` ?

**Comment by DarkBuffalo** [comment]
mu: 1.10.3

**Comment by abougouffa** [comment]
Bizarre, je suis pratiquement sur la même configuration ! Manjaro Linux, Emacs 29 et mu 1.10.3. Et je n'arrive pas à reproduire le problème.

**Comment by DarkBuffalo** [comment]
desolé pour le derangement c'était un ajout dans ma config qui etait la source de l'erreur
