### ISSUE TITLE
evil-mode '>' evil-shift-left loses selection

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#77]
hi @abougouffa 
when i move code use evil  
This operation is incoherent  
May need to be optimized
I didn't submit a pr because I think you can make them better combined
thks
https://superuser.com/questions/684540/evil-mode-evil-shift-left-loses-selection

**Comment by abougouffa** [comment]
Thank you for suggestion @donneyluck,

I really want to have this behavior, however, when I tried the code above, I got a weird behavior on right shift:

![Peek 2023-06-15 15-40](https://github.com/abougouffa/minemacs/assets/3716399/dce50dd2-1a75-4ae5-a880-9315e0574233)

**Comment by abougouffa** [comment]
After all, I think sticking with the defaults might be better, see this answer:

https://www.reddit.com/r/emacs/comments/t8zmx1/comment/hzthnb2

**Comment by donneyluck** [comment]
> After all, I think sticking with the defaults might be better, see this answer:
> 
> https://www.reddit.com/r/emacs/comments/t8zmx1/comment/hzthnb2

1. You can restore the selection by pressing gv after indenting to get the selection back.

2. If you wanted to re-indent the selection press . (no need to re-select).

Option 1 works but is cumbersome

Option 2 got an error  evil-repeat not work

**Comment by donneyluck** [comment]
> Thank you for suggestion @donneyluck,
> 
> I really want to have this behavior, however, when I tried the code above, I got a weird behavior on right shift:
> 
> ![Peek 2023-06-15 15-40](https://user-images.githubusercontent.com/3716399/246129388-dce50dd2-1a75-4ae5-a880-9315e0574233.gif)
> 
> #### Update
> The behavior depicted above is also present in `evi-shift-left`. Maybe I need to report this upstream.
I guess this problem may be caused by some hooks that automatically format buffers

**Comment by abougouffa** [comment]
The weird right shift behavior in Lisp modes was caused by `parinfer-rust-mode`, the commit a46a79f039d215d84f6fad17ba52159406ab0feb should fix this!

However, pressing "." do repeat the last command!
