### ISSUE TITLE
Parinfer-rust-mode error on m1 /  arm64

### ISSUE THREAD

**Issue by jonathanwilner** [abougouffa/minemacs#8]
The configuration of parinfer-mode & auto-downloading is hardcoded to look for x86_64.  

There isn't a pre-built artifact for arm64/arm64e for the M1/M2 Macs. 

`Installing parinfer-rust-darwin.so v0.4.4-beta to ~/.emacs.d/local/parinfer-rust/parinfer-rust-darwin.so
Error running timer: (module-open-failed "/Users/Jonathan.Wilner/.emacs.d/local/parinfer-rust/parinfer-rust-darwin.so" "dlopen(/Users/Jonathan.Wilner/.emacs.d/local/parinfer-rust/parinfer-rust-darwin.so, 0x0009): tried: '/Users/Jonathan.Wilner/.emacs.d/local/parinfer-rust/parinfer-rust-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/Jonathan.Wilner/.emacs.d/local/parinfer-rust/parinfer-rust-darwin.so' (no such file), '/Users/Jonathan.Wilner/.emacs.d/local/parinfer-rust/parinfer-rust-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))")
`

**Comment by abougouffa** [comment]
Yep, `parinfer-rust-mode` do not provide precompiled library for ARM64.

I've pushed a commit to disable loading `parinfer-rust-mode` on non `x86_64` devices. This should fix the error, and you can still compile `parinfer-rust` library from source and configure it in your `config.el`.

```elisp
(setq parinfer-rust-library "/path/to/your/parinfer-rust-library.so")
```

**Comment by mandarvaze** [comment]
@abougouffa  May be put this under FAQ - since two people (including myself) asked about this in short span 😄

**Comment by abougouffa** [comment]
@mandarvaze Good idea! Now we have an [FAQ.org file](https://github.com/abougouffa/minemacs/blob/main/FAQ.org)!

**Comment by mandarvaze** [comment]
@jonathanwilner Can you mark this issue closed ?
