### ISSUE TITLE
about  completion backends

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#84]
hi @abougouffa 
I sent both cape and corfu in the configuration
According to my understanding they are the same 
Question 1:
I want to know why you use both
Question 2:
What should I do if I want to use tabnine

Thank you for your frame and time : )

**Comment by abougouffa** [comment]
Hello @donneyluck 

### Answer 1
No, `cape` and `corfu` ARE NOT the same.

Corfu = COmpletion in Region FUnction: it allows to display completion candidates in a popup.

Cape = Completion At Point Extension: it is a set of completion backends/extensions to use for `completion-at-point-functions`.

The two packages are complementary, as both at built on top of the built-in Capf (Completion at point functions) mechanism.

### Answer 2
I don't know, never heard of `tabnine` before

**Comment by abougouffa** [comment]
Please use the [discussions section](https://github.com/abougouffa/minemacs/discussions) for direct questions not related to bugs.

**Comment by donneyluck** [comment]
ok i will thks
