### ISSUE TITLE
drag-stuff has no keybinding in some modes

### ISSUE THREAD

**Issue by azzamsa** [abougouffa/minemacs#94]
Hi.

In Emacs-Lisp mode, I can get `drag-stuff` keybindings:

![image](https://github.com/abougouffa/minemacs/assets/17734314/1298d6a5-90ed-4468-bd00-1654c4b73d84)

But in Javascript mode, it disappears.

![image](https://github.com/abougouffa/minemacs/assets/17734314/da0e66eb-579e-4206-af23-f0194ab747ed)

It is bonded to:

```
M-<down> runs the command combobulate-splice-down (found in
combobulate-key-map), which is an interactive native-compiled Lisp function in
‘combobulate-manipulation.el’.

It is binded to M-<down>.

(combobulate-splice-down &optional ARG)

Not documented.
```

Thanks for MinEmacs :heart:

**Comment by abougouffa** [comment]
It has been fixed in https://github.com/abougouffa/minemacs/commit/54343a485fc6414cd6a32389d8bde2c78693fc79

**Comment by azzamsa** [comment]
I think I rebing it tonuse the default keybinding.
This commit adds more keys. Which contradicts my goals of using evil.
