### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by raylemon** [abougouffa/minemacs#97]
Hello, I have this error at start

> Symbol’s function definition is void: \(setf\ internal--with-suppressed-warnings\)

**Comment by abougouffa** [comment]
Hello @raylemon , thank you for the feedback.

Can you please start Emacs as:

```shell
MINEMACS_DEBUG=1 emacs
```

And share the back trace?

**Comment by raylemon** [comment]
Debugger entered--Lisp error: (void-function \(setf\ internal--with-suppressed-warnings\))
  \(setf\ internal--with-suppressed-warnings\)((("LATIN CAPITAL LETTER YOGH" . 540) ("LATIN SMALL LETTER YOGH" . 541) ("CYRILLIC CAPITAL LETTER E" . 1069) ("CYRILLIC CAPITAL LETTER I" . 1048) ("CYRILLIC SMALL LETTER I" . 1080) ("CYRILLIC SMALL LETTER E" . 1101) ("DOUBLE VERTICAL BAR" . 9208) ("GEORGIAN SMALL LETTER AN" . 11520) ("GEORGIAN SMALL LETTER BAN" . 11521) ("GEORGIAN SMALL LETTER GAN" . 11522) ("GEORGIAN SMALL LETTER DON" . 11523) ("GEORGIAN SMALL LETTER EN" . 11524) ("GEORGIAN SMALL LETTER VIN" . 11525) ("GEORGIAN SMALL LETTER ZEN" . 11526) ("GEORGIAN SMALL LETTER TAN" . 11527) ("GEORGIAN SMALL LETTER IN" . 11528) ("GEORGIAN SMALL LETTER KAN" . 11529) ("GEORGIAN SMALL LETTER LAS" . 11530) ("GEORGIAN SMALL LETTER MAN" . 11531) ("GEORGIAN SMALL LETTER NAR" . 11532) ("GEORGIAN SMALL LETTER ON" . 11533) ("GEORGIAN SMALL LETTER PAR" . 11534) ("GEORGIAN SMALL LETTER ZHAR" . 11535) ("GEORGIAN SMALL LETTER RAE" . 11536) ("GEORGIAN SMALL LETTER SAN" . 11537) ("GEORGIAN SMALL LETTER TAR" . 11538) ("GEORGIAN SMALL LETTER UN" . 11539) ("GEORGIAN SMALL LETTER PHAR" . 11540) ("GEORGIAN SMALL LETTER KHAR" . 11541) ("GEORGIAN SMALL LETTER GHAN" . 11542) ("GEORGIAN SMALL LETTER QAR" . 11543) ("GEORGIAN SMALL LETTER SHIN" . 11544) ("GEORGIAN SMALL LETTER CHIN" . 11545) ("GEORGIAN SMALL LETTER CAN" . 11546) ("GEORGIAN SMALL LETTER JIL" . 11547) ("GEORGIAN SMALL LETTER CIL" . 11548) ("GEORGIAN SMALL LETTER CHAR" . 11549) ("GEORGIAN SMALL LETTER XAN" . 11550) ("GEORGIAN SMALL LETTER JHAN" . 11551) ("GEORGIAN SMALL LETTER HAE" . 11552) ("GEORGIAN SMALL LETTER HE" . 11553) ("GEORGIAN SMALL LETTER HIE" . 11554) ("GEORGIAN SMALL LETTER WE" . 11555) ("GEORGIAN SMALL LETTER HAR" . 11556) ("GEORGIAN SMALL LETTER HOE" . 11557) ("HANGUL LETTER KIYEOK" . 12593) ("HANGUL LETTER PIEUP" . 12610) ("HANGUL LETTER CIEUC" . 12616) ("PARENTHESIZED HANGUL KIYEOK" . 12800) ("PARENTHESIZED HANGUL PIEUP" . 12805) ...) ((lexical cl-x)) nil)
  tconc-list(#s(tconc :head nil :tail nil) (("LATIN CAPITAL LETTER YOGH" . 540) ("LATIN SMALL LETTER YOGH" . 541) ("CYRILLIC CAPITAL LETTER E" . 1069) ("CYRILLIC CAPITAL LETTER I" . 1048) ("CYRILLIC SMALL LETTER I" . 1080) ("CYRILLIC SMALL LETTER E" . 1101) ("DOUBLE VERTICAL BAR" . 9208) ("GEORGIAN SMALL LETTER AN" . 11520) ("GEORGIAN SMALL LETTER BAN" . 11521) ("GEORGIAN SMALL LETTER GAN" . 11522) ("GEORGIAN SMALL LETTER DON" . 11523) ("GEORGIAN SMALL LETTER EN" . 11524) ("GEORGIAN SMALL LETTER VIN" . 11525) ("GEORGIAN SMALL LETTER ZEN" . 11526) ("GEORGIAN SMALL LETTER TAN" . 11527) ("GEORGIAN SMALL LETTER IN" . 11528) ("GEORGIAN SMALL LETTER KAN" . 11529) ("GEORGIAN SMALL LETTER LAS" . 11530) ("GEORGIAN SMALL LETTER MAN" . 11531) ("GEORGIAN SMALL LETTER NAR" . 11532) ("GEORGIAN SMALL LETTER ON" . 11533) ("GEORGIAN SMALL LETTER PAR" . 11534) ("GEORGIAN SMALL LETTER ZHAR" . 11535) ("GEORGIAN SMALL LETTER RAE" . 11536) ("GEORGIAN SMALL LETTER SAN" . 11537) ("GEORGIAN SMALL LETTER TAR" . 11538) ("GEORGIAN SMALL LETTER UN" . 11539) ("GEORGIAN SMALL LETTER PHAR" . 11540) ("GEORGIAN SMALL LETTER KHAR" . 11541) ("GEORGIAN SMALL LETTER GHAN" . 11542) ("GEORGIAN SMALL LETTER QAR" . 11543) ("GEORGIAN SMALL LETTER SHIN" . 11544) ("GEORGIAN SMALL LETTER CHIN" . 11545) ("GEORGIAN SMALL LETTER CAN" . 11546) ("GEORGIAN SMALL LETTER JIL" . 11547) ("GEORGIAN SMALL LETTER CIL" . 11548) ("GEORGIAN SMALL LETTER CHAR" . 11549) ("GEORGIAN SMALL LETTER XAN" . 11550) ("GEORGIAN SMALL LETTER JHAN" . 11551) ("GEORGIAN SMALL LETTER HAE" . 11552) ("GEORGIAN SMALL LETTER HE" . 11553) ("GEORGIAN SMALL LETTER HIE" . 11554) ("GEORGIAN SMALL LETTER WE" . 11555) ("GEORGIAN SMALL LETTER HAR" . 11556) ("GEORGIAN SMALL LETTER HOE" . 11557) ("HANGUL LETTER KIYEOK" . 12593) ("HANGUL LETTER PIEUP" . 12610) ("HANGUL LETTER CIEUC" . 12616) ("PARENTHESIZED HANGUL KIYEOK" . 12800) ("PARENTHESIZED HANGUL PIEUP" . 12805) ...))
  ucs-utils-names()
  ucs-utils-names-hash()
  ucs-utils--lookup("Symbol for Escape")
  ucs-utils-char("Symbol for Escape" nil)
  unicode-fonts--generate-instructions("fontset-default")
  unicode-fonts--load-or-generate-instructions("fontset-default" nil)
  unicode-fonts--setup-1("fontset-default" nil)
  unicode-fonts-setup()
  (progn (select-frame frame 'norecord) (let* ((unicode-font-family (and t (plist-get minemacs-fonts :unicode-font-family)))) (if unicode-font-family (let ((tail unicode-fonts-block-font-mapping)) (while tail (let ((unicode-block ...)) (let* (...) (setcar ... ...)) (setq tail (cdr tail))))) nil)) (unicode-fonts-setup))
  (unwind-protect (progn (select-frame frame 'norecord) (let* ((unicode-font-family (and t (plist-get minemacs-fonts :unicode-font-family)))) (if unicode-font-family (let ((tail unicode-fonts-block-font-mapping)) (while tail (let (...) (let* ... ...) (setq tail ...)))) nil)) (unicode-fonts-setup)) (if (frame-live-p old-frame) (progn (select-frame old-frame 'norecord))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer))))
  (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame frame 'norecord) (let* ((unicode-font-family (and t (plist-get minemacs-fonts :unicode-font-family)))) (if unicode-font-family (let ((tail unicode-fonts-block-font-mapping)) (while tail (let ... ... ...))) nil)) (unicode-fonts-setup)) (if (frame-live-p old-frame) (progn (select-frame old-frame 'norecord))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer)))))
  (progn (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame frame 'norecord) (let* ((unicode-font-family (and t ...))) (if unicode-font-family (let (...) (while tail ...)) nil)) (unicode-fonts-setup)) (if (frame-live-p old-frame) (progn (select-frame old-frame 'norecord))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer))))))
  (if (display-multi-font-p frame) (progn (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame frame 'norecord) (let* ((unicode-font-family ...)) (if unicode-font-family (let ... ...) nil)) (unicode-fonts-setup)) (if (frame-live-p old-frame) (progn (select-frame old-frame 'norecord))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer)))))))
  (if frame (if (display-multi-font-p frame) (progn (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame frame 'norecord) (let* (...) (if unicode-font-family ... nil)) (unicode-fonts-setup)) (if (frame-live-p old-frame) (progn (select-frame old-frame ...))) (if (buffer-live-p old-buffer) (progn (set-buffer old-buffer))))))) nil)
  (let* ((frame (and t (selected-frame)))) (if frame (if (display-multi-font-p frame) (progn (let ((old-frame (selected-frame)) (old-buffer (current-buffer))) (unwind-protect (progn (select-frame frame ...) (let* ... ...) (unicode-fonts-setup)) (if (frame-live-p old-frame) (progn ...)) (if (buffer-live-p old-buffer) (progn ...)))))) nil))
  +unicode-fonts-setup()
  run-hooks(minemacs-after-startup-hook)
  (progn (setq minemacs-after-startup-hook (reverse minemacs-after-startup-hook)) (let ((inhibit-message t)) (apply #'message (list (concat "[MinEmacs:Log] " "Running %d `minemacs-after-startup-hook' hooks.") (length minemacs-after-startup-hook)))) (run-hooks 'minemacs-after-startup-hook))
  (if minemacs-after-startup-hook (progn (setq minemacs-after-startup-hook (reverse minemacs-after-startup-hook)) (let ((inhibit-message t)) (apply #'message (list (concat "[MinEmacs:Log] " "Running %d `minemacs-after-startup-hook' hooks.") (length minemacs-after-startup-hook)))) (run-hooks 'minemacs-after-startup-hook)))
  load-with-code-conversion("/home/ray/.emacs.d/core/minemacs-loaded.el" "/home/ray/.emacs.d/core/minemacs-loaded.el" nil t)
  require(minemacs-loaded)
  +minemacs--loaded-h()
  run-hooks(emacs-startup-hook term-setup-hook)
  #f(compiled-function () #<bytecode -0xb302ea926610e9>)()
  normal-top-level()

**Comment by abougouffa** [comment]
Merci pour le retour.

Pouvez-vous essayer avec Emacs 29 après avoir supprimé le dossier `~/.emacs.d/local/cache/pcache`? 
J'ai eu précédemment des problèmes avec le package `unicode-fonts` sur Emacs 30.

En tout cas, vous pouvez désactiver ce package en l'ajoutant à la liste `minemacs-disabled-packages` dans `modules.el`.

```elisp
;; Dans ~/.minemacs.d/modules.el
(push 'unicode-fonts minemacs-disabled-packages)
```
